#!/usr/bin/env python3
"""Record an exact-spec packet response; this tool does not authorize actions.

New summaries contain a canonical spec digest and option values. Resolve the
current spec explicitly with --spec, or from one unambiguous filed spec. The
human text must equal the text generated by that spec and those selections.

    python3 record_rulings.py paste.txt --spec packet-spec.json --file-into DIR
    python3 record_rulings.py paste.txt --spec packet-spec.json --stdout
    python3 record_rulings.py old-paste.txt --legacy-unbound --stdout

--provenance accepts a JSON object with principal, source_ref, received_at,
scope and authority_ref strings. These are claimed provenance, never verified
identity. The existing action owner verifies the trusted instruction and exact
operation. Every emitted record explicitly grants no action authority.
Legacy text stays readable but cannot be converted into a new bound record.
Existing files are preserved; revised responses receive distinct filenames.
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import pathlib
import re
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))
from build_packet import (parse_iso_date, slugify, strict_json, spec_digest,
                          validate, write_preserved)  # noqa: E402

# The format, literal by literal. test_build_packet.py asserts every entry of
# JS_FORMAT_LITERALS appears in renderSummary(), so this file and the packet's
# JavaScript cannot drift apart silently.
UNDECIDED = "— not yet decided"
TOOK = "  (took the recommendation)"
BULK = "  (accepted in bulk)"
OVERRODE = "  (OVERRODE: recommended "
DECISION_PREFIX = "    -> "
NOTE_PREFIX = "    note: "
ID_LABEL_SEP = "  "
DECIDED_LINE = "Decided {decided} of {total}."
BULK_TRAILER = (" of those were accepted in bulk rather than considered one by one — "
                "weight them accordingly.")
STORAGE_TRAILER = "(This browser blocked local storage, so nothing was saved between sittings.)"

JS_FORMAT_LITERALS = (
    '"— not yet decided"',
    '"  (took the recommendation)"',
    '"  (accepted in bulk)"',
    '"  (OVERRODE: recommended "',
    '"    -> "',
    '"    note: "',
    '"Decided "',
    '" of those were accepted in bulk rather than considered one by one — "',
    '"weight them accordingly."',
    '"(This browser blocked local storage, so nothing was saved between sittings.)"',
)

DECIDED_RE = re.compile(r"Decided (\d+) of (\d+)\.")
BULK_TRAILER_RE = re.compile(r"(\d+)" + re.escape(BULK_TRAILER))
MARK_RE = re.compile(
    r"(.*?)(?:  \((took the recommendation|accepted in bulk|OVERRODE: recommended (.+))\))?")

FIRST_LINE_MESSAGE = (
    "the pasted text does not start with a packet summary: the first line must be the "
    'packet title and the second line the same number of "=" characters, exactly as the '
    'packet\'s "Copy summary" button produces (got first line: {got!r})'
)
WHOLE_SUMMARY = "paste the whole summary, unedited, through its last line"


class SummaryError(ValueError):
    """The pasted text is not a packet summary in the button's format."""


def js_length(text: str) -> int:
    """The length JavaScript reports for `text`: UTF-16 code units, so a
    character outside the Basic Multilingual Plane (an emoji) counts as two.
    The page underlines the title with "=".repeat(SPEC.title.length)."""
    return len(text.encode("utf-16-le")) // 2


# ---------------------------------------------------------------------------
# The format in Python: what renderSummary() emits for a given spec and state
# ---------------------------------------------------------------------------

def compose_legacy_summary(spec: dict, state: dict, storage_blocked: bool = False) -> str:
    """Render the summary the packet's button would emit.

    `state` maps row id -> {"choice": option value, "note": str, "bulk": bool},
    each key optional, mirroring the packet's saved state.
    """
    title = str(spec["title"])
    lines = [title, "=" * js_length(title), ""]
    decided = 0
    bulk = 0
    for row in spec["rows"]:
        saved = state.get(row["id"], {})
        choice = saved.get("choice")
        options = row.get("options") or spec["options"]

        def label_for(value):
            for o in options:
                if o.get("value") == value:
                    return str(o["label"])
            return str(value)

        if choice is not None:
            decided += 1
        mark = UNDECIDED if choice is None else label_for(choice)
        if choice is not None and row.get("recommendation"):
            if choice != row["recommendation"]:
                mark += OVERRODE + label_for(row["recommendation"]) + ")"
            else:
                mark += BULK if saved.get("bulk") else TOOK
        if saved.get("bulk"):
            bulk += 1
        lines.append(str(row["id"]) + ID_LABEL_SEP + str(row["label"]))
        lines.append(DECISION_PREFIX + mark)
        note = str(saved.get("note") or "")
        if js_trim(note):
            lines.append(NOTE_PREFIX + js_trim(note))
        lines.append("")
    lines.append(DECIDED_LINE.format(decided=decided, total=len(spec["rows"])))
    if bulk:
        lines.append(f"{bulk}{BULK_TRAILER}")
    if storage_blocked:
        lines.append(STORAGE_TRAILER)
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Parsing
# ---------------------------------------------------------------------------

def _parse_mark(rid: str, label: str, mark: str, line_no: int) -> dict:
    ruling = {
        "id": rid,
        "label": label,
        "choice_label": None,
        "took_recommendation": None,
        "accepted_in_bulk": False,
        "recommended_label": None,
        "note": None,
    }
    if mark == UNDECIDED:
        return ruling
    m = MARK_RE.fullmatch(mark)
    choice, suffix, recommended = m.group(1), m.group(2), m.group(3)
    if not choice:
        raise SummaryError(f"line {line_no}: the decision line names no option: {mark!r}")
    ruling["choice_label"] = choice
    if suffix == "took the recommendation":
        ruling["took_recommendation"] = True
        ruling["recommended_label"] = choice
    elif suffix == "accepted in bulk":
        ruling["took_recommendation"] = True
        ruling["accepted_in_bulk"] = True
        ruling["recommended_label"] = choice
    elif suffix is not None:
        ruling["took_recommendation"] = False
        ruling["recommended_label"] = recommended
    return ruling


def _parse_legacy_summary(text: str) -> dict:
    """Parse a pasted summary into {packet, decided, total, rulings}.

    Raises SummaryError, whose message names the line that failed and the form
    expected there.
    """
    lines = [line if line.strip() else ""
             for line in text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    if len(lines) < 2 or not lines[0] or lines[1] != "=" * js_length(lines[0]):
        raise SummaryError(FIRST_LINE_MESSAGE.format(got=lines[0] if lines else ""))
    title = lines[0]

    terminal = None
    for i in range(len(lines) - 1, 1, -1):
        m = DECIDED_RE.fullmatch(lines[i])
        if m:
            terminal = i
            break
    if terminal is None:
        raise SummaryError(f'no "Decided <n> of <m>." line - {WHOLE_SUMMARY}')
    decided_n, total_n = int(m.group(1)), int(m.group(2))
    for offset, extra in enumerate(lines[terminal + 1:], start=terminal + 2):
        if extra == STORAGE_TRAILER or BULK_TRAILER_RE.fullmatch(extra):
            continue
        raise SummaryError(f"line {offset}: unexpected text after the Decided line: {extra!r}")

    body = lines[2:terminal]  # body[i] is line i + 3
    if not body or body[0] != "":
        raise SummaryError(
            "line 3: expected a blank line after the title underline, got "
            f"{body[0] if body else lines[terminal]!r}")
    headers = [
        i for i in range(1, len(body) - 1)
        if body[i - 1] == "" and body[i] and not body[i][0].isspace()
        and body[i + 1].startswith(DECISION_PREFIX)
    ]
    rulings = []
    for k, h in enumerate(headers):
        end = headers[k + 1] - 1 if k + 1 < len(headers) else len(body)
        header = body[h]
        if ID_LABEL_SEP not in header:
            raise SummaryError(f"line {h + 3}: expected '<id>  <label>', got {header!r}")
        rid, label = header.split(ID_LABEL_SEP, 1)
        ruling = _parse_mark(rid, label, body[h + 1][len(DECISION_PREFIX):], h + 4)
        # After the decision line the page emits either the note, or the blank
        # that closes the block. Anything else between here and the next row
        # header is content the format has no place for: a stray line, or a
        # would-be header whose decision line is missing. Blank lines are
        # skipped so the refusal quotes the offending content, never a blank.
        j = h + 2
        while j < end and body[j] == "":
            j += 1
        rest = body[j:end]
        while rest and rest[-1] == "":
            rest.pop()
        if rest:
            if not rest[0].startswith(NOTE_PREFIX):
                raise SummaryError(
                    f"line {j + 3}: expected '{NOTE_PREFIX}' or the next row header "
                    f"('<id>  <label>' followed by a '{DECISION_PREFIX}' line) after the "
                    f"decision line, got {rest[0]!r}")
            ruling["note"] = "\n".join([rest[0][len(NOTE_PREFIX):]] + rest[1:])
        rulings.append(ruling)

    if len(rulings) != total_n:
        raise SummaryError(
            f"the Decided line says {total_n} rows but {len(rulings)} row blocks were found - "
            f"{WHOLE_SUMMARY}")
    decided_found = sum(1 for r in rulings if r["choice_label"] is not None)
    if decided_found != decided_n:
        raise SummaryError(
            f"the Decided line says {decided_n} decided but {decided_found} rows carry a "
            f"decision - {WHOLE_SUMMARY}")
    return {"packet": title, "decided": decided_n, "total": total_n, "rulings": rulings}


BINDING_PREFIX = "Decision packet binding v2: "
SHA256 = re.compile(r"[0-9a-f]{64}")
JS_WHITESPACE = "\u0009\u000a\u000b\u000c\u000d\u0020\u00a0\u1680\u2000\u2001\u2002\u2003\u2004\u2005\u2006\u2007\u2008\u2009\u200a\u2028\u2029\u202f\u205f\u3000\ufeff"


def js_trim(text: str) -> str:
    return text.strip(JS_WHITESPACE)


def _normalized_text(text: str) -> str:
    lines = [line if line.strip() else "" for line in
             text.replace("\r\n", "\n").replace("\r", "\n").split("\n")]
    while lines and not lines[0]:
        lines.pop(0)
    while lines and not lines[-1]:
        lines.pop()
    return "\n".join(lines)


def summary_binding(text: str) -> dict | None:
    """Read untrusted transport metadata, not an authorization statement."""
    lines = _normalized_text(text).split("\n")
    if len(lines) < 2 or not lines[0] or lines[1] != "=" * js_length(lines[0]):
        raise SummaryError(FIRST_LINE_MESSAGE.format(got=lines[0] if lines else ""))
    if not lines[-1].startswith(BINDING_PREFIX):
        return None
    try:
        binding = strict_json(lines[-1][len(BINDING_PREFIX):])
    except (ValueError, UnicodeError) as exc:
        raise SummaryError(f"invalid binding JSON: {exc}") from exc
    if (not isinstance(binding, dict) or set(binding) !=
            {"schema_version", "spec_sha256", "selections", "storage_blocked"} or
            type(binding["schema_version"]) is not int or binding["schema_version"] != 2 or
            not isinstance(binding["spec_sha256"], str) or not SHA256.fullmatch(binding["spec_sha256"]) or
            not isinstance(binding["selections"], list) or type(binding["storage_blocked"]) is not bool):
        raise SummaryError("invalid schema-2 binding fields")
    return binding


def _selection_state(spec: dict, selections: list) -> dict:
    hard = [p for p in validate(spec) if not p.startswith(("NOTE:", "READER:"))]
    if hard:
        raise SummaryError("invalid current spec: " + "; ".join(hard))
    if len(selections) != len(spec["rows"]):
        raise SummaryError("binding row count does not match the current spec")
    state = {}
    for row, selected in zip(spec["rows"], selections):
        if not isinstance(selected, dict) or set(selected) != {"id", "choice", "note", "bulk"}:
            raise SummaryError("each bound selection needs exactly id, choice, note and bulk")
        rid = selected["id"]
        if not isinstance(rid, str) or rid in state:
            raise SummaryError("duplicate or invalid bound row id")
        if rid != row["id"]:
            raise SummaryError("bound row ids/order do not match the current spec")
        choice, note, bulk = selected["choice"], selected["note"], selected["bulk"]
        options = row.get("options") or spec["options"]
        if choice is not None and (not isinstance(choice, str) or
                                  choice not in {o["value"] for o in options}):
            raise SummaryError(f"row {rid}: unknown option value {choice!r}")
        if not isinstance(note, str) or type(bulk) is not bool:
            raise SummaryError(f"row {rid}: note must be a string and bulk a Boolean")
        if bulk and (choice is None or choice != row.get("recommendation")):
            raise SummaryError(f"row {rid}: bulk acceptance must take its recommendation")
        if note != js_trim(note):
            raise SummaryError(f"row {rid}: bound note differs from the trimmed displayed note")
        try:
            note.encode("utf-8")
        except UnicodeEncodeError as exc:
            raise SummaryError(f"row {rid}: invalid Unicode note") from exc
        state[rid] = {"choice": choice, "note": note, "bulk": bulk}
    return state


def compose_summary(spec: dict, state: dict, storage_blocked: bool = False) -> str:
    """The exact schema-2 output of the production JavaScript renderSummary."""
    if not isinstance(state, dict) or set(state) - {r["id"] for r in spec["rows"]}:
        raise SummaryError("state includes unknown row ids")
    selections = []
    for row in spec["rows"]:
        saved = state.get(row["id"], {})
        if not isinstance(saved, dict):
            raise SummaryError("row state must be an object")
        note = saved.get("note", "")
        if not isinstance(note, str):
            raise SummaryError("note must be a string")
        selections.append({"id": row["id"], "choice": saved.get("choice"),
                           "note": js_trim(note), "bulk": saved.get("bulk", False)})
    normalized = _selection_state(spec, selections)
    binding = {"schema_version": 2, "spec_sha256": spec_digest(spec),
               "selections": selections, "storage_blocked": storage_blocked}
    return (compose_legacy_summary(spec, normalized, storage_blocked) + "\n" + BINDING_PREFIX +
            json.dumps(binding, ensure_ascii=False, separators=(",", ":"), allow_nan=False))


def parse_summary(text: str, spec: dict | None = None) -> dict:
    binding = summary_binding(text)
    if binding is None:
        parsed = _parse_legacy_summary(text)
        ids = [r["id"] for r in parsed["rulings"]]
        if len(ids) != len(set(ids)):
            raise SummaryError("duplicate row ids in legacy summary")
        return {**parsed, "schema_version": 1, "binding": {"status": "legacy-unbound"}}
    if spec is None:
        raise SummaryError("schema-2 summary requires its exact current spec")
    hard = [p for p in validate(spec) if not p.startswith(("NOTE:", "READER:"))]
    if hard:
        raise SummaryError("invalid current spec: " + "; ".join(hard))
    if spec_digest(spec) != binding["spec_sha256"]:
        raise SummaryError("summary spec digest differs from the current spec; response is stale")
    state = _selection_state(spec, binding["selections"])
    expected = compose_summary(spec, state, binding["storage_blocked"])
    if _normalized_text(text) != _normalized_text(expected):
        raise SummaryError("summary text/rows differ from the exact current spec and selections; paste the whole summary unedited")
    rulings = []
    for row in spec["rows"]:
        saved = state[row["id"]]
        choice, rec = saved["choice"], row.get("recommendation")
        labels = {o["value"]: o["label"] for o in row.get("options") or spec["options"]}
        rulings.append({"id": row["id"], "label": row["label"],
                        "choice_value": choice, "choice_label": labels.get(choice),
                        "took_recommendation": choice == rec if choice is not None and rec is not None else None,
                        "accepted_in_bulk": saved["bulk"],
                        "recommended_label": labels.get(rec) if choice is not None else None,
                        "note": saved["note"] or None})
    return {"packet": spec["title"], "decided": sum(r["choice_value"] is not None for r in rulings),
            "total": len(rulings), "rulings": rulings, "schema_version": 2,
            "binding": {"status": "spec-bound", "spec_sha256": binding["spec_sha256"]}}


def _current_spec(path: pathlib.Path | None, directory: pathlib.Path | None, text: str) -> tuple[dict, pathlib.Path, str]:
    if path is None:
        title = _normalized_text(text).split("\n")[0]
        candidates = []
        for candidate in sorted(directory.glob("*-spec.json")) if directory else []:
            if candidate.is_symlink():
                raise SummaryError(f"refusing symlink spec: {candidate}")
            data = strict_json(candidate.read_text(encoding="utf-8"))
            if isinstance(data, dict) and data.get("title") == title:
                candidates.append(candidate)
        if len(candidates) != 1:
            raise SummaryError("need one current *-spec.json, or --spec PATH to select it explicitly; "
                               f"found {len(candidates)} candidates")
        path = candidates[0]
    if path.is_symlink() or not path.is_file():
        raise SummaryError(f"unsafe or missing spec: {path}")
    raw = path.read_bytes()
    return strict_json(raw.decode("utf-8")), path, hashlib.sha256(raw).hexdigest()


def _provenance(path: pathlib.Path | None) -> dict:
    fields = {"principal", "source_ref", "received_at", "scope", "authority_ref"}
    if path is None:
        return {"status": "unattributed-paste", **{key: None for key in sorted(fields)}}
    if path.is_symlink() or not path.is_file():
        raise SummaryError("unsafe or missing provenance file")
    raw = path.read_bytes()
    data = strict_json(raw.decode("utf-8"))
    if (not isinstance(data, dict) or set(data) != fields or
            not all(isinstance(v, str) and v.strip() for v in data.values())):
        raise SummaryError("provenance requires principal, source_ref, received_at, scope and authority_ref strings")
    try:
        received = datetime.datetime.fromisoformat(data["received_at"].replace("Z", "+00:00"))
        if received.tzinfo is None:
            raise ValueError("timezone required")
    except ValueError as exc:
        raise SummaryError("provenance received_at must be a timezone-aware ISO timestamp") from exc
    return {"status": "claimed-unverified", **data, "file_sha256": hashlib.sha256(raw).hexdigest()}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
                                 allow_abbrev=False)
    ap.add_argument("paste", help="file holding the summary ('-' for stdin)")
    ap.add_argument("--file-into", type=pathlib.Path, metavar="DIR", help="existing owning project's resources/artifacts/")
    ap.add_argument("--spec", type=pathlib.Path, help="exact current spec to validate")
    ap.add_argument("--provenance", type=pathlib.Path, help="claimed provenance JSON; does not authenticate the principal")
    ap.add_argument("--date", metavar="YYYY-MM-DD", help="record date (default: today); not proof of decision time")
    ap.add_argument("--legacy-unbound", action="store_true", help="read historical text to stdout only, without binding or authority")
    ap.add_argument("--stdout", action="store_true")
    args = ap.parse_args()
    if not args.file_into and not args.stdout:
        ap.error("pass --file-into DIR or --stdout")
    if args.date and parse_iso_date(args.date) is None:
        ap.error(f"--date {args.date!r} is not a calendar date in YYYY-MM-DD form")
    if args.file_into and not args.file_into.is_dir():
        ap.error(f"--file-into: {args.file_into} is not an existing directory; use the owning project's resources/artifacts/")
    if args.legacy_unbound and (args.file_into or args.spec or args.provenance):
        ap.error("--legacy-unbound is a stdout-only historical read; it cannot bind, file or authorize")
    try:
        raw = sys.stdin.read() if args.paste == "-" else pathlib.Path(args.paste).read_text(encoding="utf-8")
        binding = summary_binding(raw)
        if binding is None and not args.legacy_unbound:
            raise SummaryError("legacy summary has no exact-spec binding; use --legacy-unbound --stdout to read history. "
                               "Existing user grants remain with their trusted source and action owner.")
        if binding is not None and args.legacy_unbound:
            raise SummaryError("schema-2 text is not a legacy summary")
        spec_info = None
        if binding is not None:
            spec, path, file_digest = _current_spec(args.spec, args.file_into, raw)
            parsed = parse_summary(raw, spec)
            spec_info = {"file": path.name, "file_sha256": file_digest,
                         "canonical_sha256": parsed["binding"]["spec_sha256"]}
        else:
            parsed = parse_summary(raw)
        record = {**parsed, "ruled_on": args.date or datetime.date.today().isoformat(),
                  "spec": spec_info, "summary_sha256": hashlib.sha256(raw.encode("utf-8")).hexdigest(),
                  "provenance": _provenance(args.provenance),
                  "authorization": {"granted": False, "authentication": "unverified",
                                    "owner": "existing action owner must verify trusted authority and exact operation"}}
        payload = (json.dumps(record, indent=2, ensure_ascii=False, allow_nan=False) + "\n").encode("utf-8")
        if args.file_into:
            stem = f"{record['ruled_on']}-{slugify(record['packet'])}"
            dest = args.file_into / f"{stem}-rulings.json"
            if dest.is_symlink():
                raise SummaryError("refusing symlink rulings output")
            if dest.exists() and dest.read_bytes() != payload:
                dest = args.file_into / f"{stem}-{hashlib.sha256(payload).hexdigest()}-rulings.json"
            write_preserved(dest, payload)
            print(f"filed {dest}  ({record['decided']} of {record['total']} decided; no action authority granted)",
                  file=sys.stderr if args.stdout else sys.stdout)
        if args.stdout:
            sys.stdout.write(payload.decode("utf-8"))
    except (OSError, ValueError, UnicodeError) as exc:
        print(f"record_rulings: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
