#!/usr/bin/env python3
"""Propagate a user-owned agent kernel after its source changes.

The onboarding engine installs this script and whole_system.py together under
~/.synthesis/onboarding/bin. Hook mode is quiet unless the canonical source
changed. It validates the 55 KB budget before touching either generated file,
refuses to overwrite a user-edited output, and updates receipts atomically only
after both client files reach the same source state.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path

from whole_system import KERNEL_HARD_LIMIT, kernel_budget, rendered_kernel


GENERATED_MARK = "generated by synthesis-onboarding"


def sha256_text(content: str) -> str:
    return hashlib.sha256(content.encode("utf-8")).hexdigest()


def home_path() -> Path:
    return Path(os.environ.get("SYNTHESIS_ONBOARD_HOME", str(Path.home())))


def state_path(home: Path) -> Path:
    root = Path(
        os.environ.get(
            "SYNTHESIS_ONBOARD_STATE_DIR",
            str(home / ".synthesis" / "onboarding"),
        )
    )
    return root / "receipts.json"


def atomic_write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_name(".%s.tmp-%s" % (path.name, os.getpid()))
    temporary.write_text(content, encoding="utf-8")
    os.replace(temporary, path)


def archive(path: Path, state_dir: Path) -> None:
    stamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    target = state_dir / "backups" / stamp / path.name
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(path, target)


def load_receipts(path: Path) -> dict:
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError("receipts must contain a JSON object")
    if not isinstance(data.get("generated_files"), dict):
        raise ValueError("receipts.generated_files must be an object")
    return data


def recorded_sha(receipts: dict, path: Path) -> str | None:
    entry = receipts["generated_files"].get(str(path)) or {}
    return entry.get("sha256") if isinstance(entry, dict) else None


def sync(force: bool = False) -> tuple[bool, str]:
    home = home_path()
    receipt_path = state_path(home)
    try:
        receipts = load_receipts(receipt_path)
    except (OSError, ValueError) as exc:
        return False, "kernel sync cannot read onboarding receipts: %s" % exc

    workspace = receipts.get("personal_workspace")
    if not isinstance(workspace, str) or not workspace:
        return False, "kernel sync has no recorded personal workspace"
    root = home / "workspaces" / workspace
    source_path = root / "AGENTS.source.md"
    try:
        source = source_path.read_text(encoding="utf-8")
    except OSError as exc:
        return False, "kernel source is unavailable: %s" % exc
    source_sha = sha256_text(source)
    if not force and receipts.get("kernel_source_sha256") == source_sha:
        return True, "unchanged"

    size, state = kernel_budget(source)
    if state == "over":
        return (
            False,
            "kernel is %d bytes; hard limit is %d; generated files unchanged"
            % (size, KERNEL_HARD_LIMIT),
        )

    targets = {
        root / "AGENTS.md": rendered_kernel(source, "codex"),
        root / "CLAUDE.md": rendered_kernel(source, "claude"),
    }
    runs = receipts.get("runs")
    last_engine = (
        runs[-1].get("engine", "unknown")
        if isinstance(runs, list) and runs and isinstance(runs[-1], dict)
        else "unknown"
    )
    for path, wanted in targets.items():
        if not path.exists():
            continue
        try:
            current = path.read_text(encoding="utf-8")
        except OSError as exc:
            return False, "kernel output is unreadable: %s" % exc
        if current == wanted:
            continue
        if recorded_sha(receipts, path) != sha256_text(current):
            return (
                False,
                "%s has user edits; generated files unchanged" % path,
            )

    for path, wanted in targets.items():
        if path.exists() and path.read_text(encoding="utf-8") != wanted:
            archive(path, receipt_path.parent)
        atomic_write(path, wanted)
        receipts["generated_files"][str(path)] = {
            "sha256": sha256_text(wanted),
            "kind": "agent-kernel",
            "written_at": datetime.now(timezone.utc).strftime(
                "%Y-%m-%dT%H:%M:%SZ"
            ),
            "engine": last_engine,
        }
    receipts["kernel_source_sha256"] = source_sha
    atomic_write(receipt_path, json.dumps(receipts, indent=2, sort_keys=True) + "\n")
    return True, "synchronized %s" % source_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--hook", action="store_true", help="quiet no-op when source is unchanged")
    parser.add_argument("--force", action="store_true", help="check and render even if the source hash matches")
    args = parser.parse_args(argv)
    ok, detail = sync(force=args.force)
    if detail != "unchanged":
        stream = sys.stdout if ok else sys.stderr
        print(detail, file=stream)
    return 0 if ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
