#!/usr/bin/env python3
"""Security, state, provenance, and outcome contracts for synthesis onboarding.

This module is Python-standard-library only.  It is shared by the bootstrap,
the public CLI, the compatibility engine, and the release gate so those entry
points cannot invent separate trust or receipt rules.
"""

from __future__ import annotations

import contextlib
import fcntl
import hashlib
import json
import os
import re
import shlex
import stat
import subprocess
import tempfile
import uuid
from datetime import datetime, timezone
from pathlib import Path, PurePosixPath
from typing import Any, Callable, Iterator
from urllib.parse import urlsplit


SCHEMA_VERSION = 1
OBSERVATION_SCHEMA_VERSION = 3
TREE_POLICY = "regular-files-and-directories-no-links-v1"
DIGEST_ALGORITHM = "sha256-tree-v1"
TRUTH_PLANES = (
    "desired",
    "resolved",
    "installed",
    "source-provenance",
    "live-loaded",
    "outcome-verified",
)
TRANSACTION_COMMANDS = {"setup", "update", "repair", "workspace-ensure", "uninstall"}
SAFE_IDENTIFIER_RE = re.compile(r"^[a-z0-9][a-z0-9-]{0,62}$")
VERSION_RE = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
HEX40_RE = re.compile(r"^[0-9a-f]{40}$")
HEX64_RE = re.compile(r"^[0-9a-f]{64}$")
LAUNCHER_MARK = "# generated by synthesis-onboarding; managed file"
CONTRACT_FILES = {
    "release": "release-descriptor.schema.json",
    "desired": "system-state.schema.json",
    "observation": "machine-observation.schema.json",
    "invite": "invite.schema.json",
    "instructions": "instruction-sources.schema.json",
    "capabilities": "release-capabilities.json",
}
LAYER_IDS = (
    "skills",
    "session-context",
    "hooks-gates",
    "agent-kernel",
    "runtime-engines",
    "coordination",
    "doctors-conformance",
    "personal-policy",
    "organization",
    "knowledge-bases",
    "lifecycle",
)
PROFILE_LAYERS = {
    "full": frozenset(LAYER_IDS) - {"organization"},
    "skills-only": frozenset({"skills", "session-context", "lifecycle"}),
}


class ContractError(ValueError):
    """Input or materialized state violates a fail-closed contract."""


class DriftError(ContractError):
    """A receipt-owned output no longer matches its last written digest."""


def utcnow() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _json_bytes(value: Any) -> bytes:
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode("utf-8")


def json_digest(value: Any) -> str:
    compact = json.dumps(value, sort_keys=True, separators=(",", ":"), ensure_ascii=False)
    return hashlib.sha256(compact.encode("utf-8")).hexdigest()


def file_digest(path: Path) -> str:
    digest = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for chunk in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _fsync_directory(path: Path) -> None:
    try:
        descriptor = os.open(str(path), os.O_RDONLY)
    except OSError:
        return
    try:
        os.fsync(descriptor)
    except OSError:
        pass
    finally:
        os.close(descriptor)


def atomic_write_bytes(path: Path, content: bytes, mode: int = 0o600) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    temporary_name = None
    try:
        with tempfile.NamedTemporaryFile(
            mode="wb",
            dir=path.parent,
            prefix=path.name + ".",
            suffix=".tmp",
            delete=False,
        ) as temporary:
            temporary_name = temporary.name
            temporary.write(content)
            temporary.flush()
            os.fsync(temporary.fileno())
        os.chmod(temporary_name, mode)
        os.replace(temporary_name, path)
        _fsync_directory(path.parent)
    finally:
        if temporary_name and os.path.exists(temporary_name):
            os.unlink(temporary_name)


def atomic_write_json(path: Path, value: Any, mode: int = 0o600) -> None:
    atomic_write_bytes(path, _json_bytes(value), mode=mode)


def safe_identifier(value: Any, label: str = "identifier") -> str:
    if not isinstance(value, str) or not SAFE_IDENTIFIER_RE.fullmatch(value):
        raise ContractError(
            "%s must contain lowercase letters, numbers, or internal hyphens only" % label
        )
    return value


def safe_relative_path(value: Any, label: str = "path") -> str:
    if not isinstance(value, str) or not value or "\\" in value:
        raise ContractError("%s must be a non-empty POSIX relative path" % label)
    path = PurePosixPath(value)
    if path.is_absolute() or any(part in ("", ".", "..") for part in path.parts):
        raise ContractError("%s must remain inside its declared repository" % label)
    return value


def contained_path(root: Path, relative: str, label: str = "path") -> Path:
    safe_relative_path(relative, label)
    root = Path(root).resolve()
    candidate = root.joinpath(*PurePosixPath(relative).parts)
    try:
        resolved = candidate.resolve(strict=False)
        resolved.relative_to(root)
    except (OSError, ValueError):
        raise ContractError("%s escapes its declared repository" % label)
    current = root
    for part in PurePosixPath(relative).parts:
        current = current / part
        if current.is_symlink():
            raise ContractError("%s traverses a symbolic link" % label)
    return candidate


def validate_repository_url(url: Any) -> str:
    if not isinstance(url, str) or not url:
        raise ContractError("repository URL is required")
    if re.fullmatch(r"[A-Za-z0-9._-]+@[A-Za-z0-9.-]+:[A-Za-z0-9._~/-]+", url):
        return url
    parsed = urlsplit(url)
    if parsed.scheme not in ("https", "ssh") or not parsed.hostname:
        raise ContractError("repository transport must be authenticated HTTPS or SSH")
    if parsed.password is not None:
        raise ContractError("repository URLs must not contain credentials")
    if parsed.scheme == "https" and parsed.username is not None:
        raise ContractError("repository URLs must not contain credentials")
    if parsed.query or parsed.fragment:
        raise ContractError("repository URL must not contain a query or fragment")
    return url


def _require_mapping(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ContractError("%s must be a mapping" % label)
    return value


def _reject_unknown(mapping: dict[str, Any], allowed: set[str], label: str) -> None:
    unknown = sorted(set(mapping) - allowed)
    if unknown:
        raise ContractError("%s has unknown keys: %s" % (label, ", ".join(unknown)))


def validate_org_manifest(data: Any, path: Path | str = "manifest") -> dict[str, Any]:
    """Validate declarative organization schema 2.

    The schema intentionally has no executable, argument, environment, or
    status-command fields.  Every action is a capability owned by this engine.
    """
    data = _require_mapping(data, "manifest")
    _reject_unknown(
        data,
        {
            "version",
            "org",
            "ecosystem",
            "skills_repos",
            "knowledge_bases",
            "instruction_sources",
            "acceptance",
            "auth_help",
            "welcome",
        },
        "manifest",
    )
    if data.get("version") != 2:
        raise ContractError("manifest version must be 2")
    org = _require_mapping(data.get("org"), "org")
    _reject_unknown(org, {"id", "name", "workspace"}, "org")
    safe_identifier(org.get("id"), "org.id")
    safe_identifier(org.get("workspace"), "org.workspace")

    ecosystem = _require_mapping(data.get("ecosystem") or {}, "ecosystem")
    _reject_unknown(ecosystem, {"plugin", "clients", "channel", "version_pin"}, "ecosystem")
    if not isinstance(ecosystem.get("plugin", True), bool):
        raise ContractError("ecosystem.plugin must be true or false")
    clients = ecosystem.get("clients", ["claude", "codex"])
    if not isinstance(clients, list) or not clients or set(clients) - {"claude", "codex"}:
        raise ContractError("ecosystem.clients must contain only claude and codex")
    channel = ecosystem.get("channel", "stable")
    if channel not in ("stable", "edge"):
        raise ContractError("ecosystem.channel must be stable or edge")
    pin = ecosystem.get("version_pin")
    if pin is not None and (not isinstance(pin, str) or not VERSION_RE.fullmatch(pin)):
        raise ContractError("ecosystem.version_pin must be an exact X.Y.Z version")

    for index, entry in enumerate(data.get("skills_repos") or []):
        entry = _require_mapping(entry, "skills_repos[%d]" % index)
        _reject_unknown(entry, {"name", "repository", "capability"}, "skills_repos[%d]" % index)
        safe_identifier(entry.get("name"), "skills_repos[%d].name" % index)
        validate_repository_url(entry.get("repository"))
        if entry.get("capability") != "skills-install":
            raise ContractError("skills_repos[%d].capability must be skills-install" % index)

    for index, entry in enumerate(data.get("knowledge_bases") or []):
        entry = _require_mapping(entry, "knowledge_bases[%d]" % index)
        _reject_unknown(
            entry,
            {"name", "repository", "default_branch", "local_hooks"},
            "knowledge_bases[%d]" % index,
        )
        safe_identifier(entry.get("name"), "knowledge_bases[%d].name" % index)
        validate_repository_url(entry.get("repository"))
        branch = entry.get("default_branch", "main")
        if not isinstance(branch, str) or not re.fullmatch(r"[A-Za-z0-9._/-]+", branch) or ".." in branch:
            raise ContractError("knowledge_bases[%d].default_branch is unsafe" % index)
        if not isinstance(entry.get("local_hooks", False), bool):
            raise ContractError("knowledge_bases[%d].local_hooks must be boolean" % index)

    instruction_sources = data.get("instruction_sources") or []
    if not isinstance(instruction_sources, list) or len(instruction_sources) != 1:
        raise ContractError("manifest needs exactly one tracked instruction source")
    for index, entry in enumerate(instruction_sources):
        entry = _require_mapping(entry, "instruction_sources[%d]" % index)
        _reject_unknown(entry, {"path", "required"}, "instruction_sources[%d]" % index)
        safe_relative_path(entry.get("path"), "instruction_sources[%d].path" % index)
        if not isinstance(entry.get("required", True), bool):
            raise ContractError("instruction_sources[%d].required must be boolean" % index)

    acceptance = _require_mapping(data.get("acceptance") or {}, "acceptance")
    _reject_unknown(acceptance, {"task"}, "acceptance")
    if acceptance:
        safe_identifier(acceptance.get("task"), "acceptance.task")
    auth_help = data.get("auth_help")
    if auth_help is not None and not isinstance(auth_help, str):
        raise ContractError("auth_help must be text")
    welcome = _require_mapping(data.get("welcome") or {}, "welcome")
    _reject_unknown(welcome, {"title", "try_asking", "docs"}, "welcome")
    for key in ("try_asking", "docs"):
        values = welcome.get(key, [])
        if not isinstance(values, list) or not all(isinstance(item, str) for item in values):
            raise ContractError("welcome.%s must be a list of text" % key)
    result = dict(data)
    result["_path"] = str(path)
    return result


def load_contract_documents(repo_root: Path) -> dict[str, dict[str, Any]]:
    references = Path(repo_root) / "skills" / "synthesis-onboarding" / "references"
    documents: dict[str, dict[str, Any]] = {}
    for key, filename in CONTRACT_FILES.items():
        path = references / filename
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ContractError("contract %s is unreadable: %s" % (filename, exc))
        if not isinstance(value, dict):
            raise ContractError("contract %s must be a JSON object" % filename)
        documents[key] = value
    capabilities = documents["capabilities"]
    if capabilities.get("schema_version") != SCHEMA_VERSION:
        raise ContractError("release capabilities schema_version must be 1")
    if tuple(capabilities.get("truth_planes") or []) != TRUTH_PLANES:
        raise ContractError("release capabilities truth planes drifted from the engine")
    expected_versions = {
        "state_schema_version": documents["desired"].get("properties", {}).get("schema_version", {}).get("const"),
        "observation_schema_version": documents["observation"].get("properties", {}).get("schema_version", {}).get("const"),
        "invite_schema_version": documents["invite"].get("properties", {}).get("schema_version", {}).get("const"),
        "instruction_sources_schema_version": documents["instructions"].get("properties", {}).get("schema_version", {}).get("const"),
    }
    for field, version in expected_versions.items():
        if capabilities.get(field) != version:
            raise ContractError("release capabilities %s disagrees with its schema" % field)
    return documents


def _iter_tree(root: Path) -> Iterator[tuple[str, os.stat_result, Path]]:
    root = Path(root)
    if not root.is_dir() or root.is_symlink():
        raise ContractError("release root must be a real directory")
    for directory, dirnames, filenames in os.walk(root, topdown=True, followlinks=False):
        current = Path(directory)
        kept_dirs = []
        for name in sorted(dirnames):
            path = current / name
            relative = path.relative_to(root).as_posix()
            if relative == ".git":
                continue
            metadata = path.lstat()
            if stat.S_ISLNK(metadata.st_mode):
                raise ContractError("release tree contains a symbolic link: %s" % relative)
            if not stat.S_ISDIR(metadata.st_mode):
                raise ContractError("release tree contains a special object: %s" % relative)
            kept_dirs.append(name)
            yield relative, metadata, path
        dirnames[:] = kept_dirs
        for name in sorted(filenames):
            path = current / name
            relative = path.relative_to(root).as_posix()
            if relative == ".git":
                continue
            metadata = path.lstat()
            if stat.S_ISLNK(metadata.st_mode):
                raise ContractError("release tree contains a symbolic link: %s" % relative)
            if not stat.S_ISREG(metadata.st_mode):
                raise ContractError("release tree contains a special object: %s" % relative)
            yield relative, metadata, path


def canonical_tree_digest(root: Path) -> str:
    digest = hashlib.sha256()
    for relative, metadata, path in sorted(_iter_tree(Path(root)), key=lambda item: item[0]):
        if stat.S_ISDIR(metadata.st_mode):
            digest.update(b"D\0" + relative.encode("utf-8") + b"\0")
            continue
        mode = b"755" if metadata.st_mode & stat.S_IXUSR else b"644"
        content_digest = bytes.fromhex(file_digest(path))
        digest.update(
            b"F\0"
            + relative.encode("utf-8")
            + b"\0"
            + mode
            + b"\0"
            + str(metadata.st_size).encode("ascii")
            + b"\0"
            + content_digest
        )
    return digest.hexdigest()


def canonical_tracked_tree_digest(root: Path, tracked_files: set[str]) -> str:
    """Hash exactly the Git-tracked file set, ignoring source-only build noise."""
    root = Path(root)
    directories = set()
    for relative in tracked_files:
        path = PurePosixPath(relative)
        for index in range(1, len(path.parts)):
            directories.add(PurePosixPath(*path.parts[:index]).as_posix())
    digest = hashlib.sha256()
    for relative in sorted(directories | tracked_files):
        path = contained_path(root, relative, "tracked release path")
        metadata = path.lstat()
        if relative in directories:
            if not stat.S_ISDIR(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
                raise ContractError("tracked release directory is not a real directory: %s" % relative)
            digest.update(b"D\0" + relative.encode("utf-8") + b"\0")
            continue
        if not stat.S_ISREG(metadata.st_mode) or stat.S_ISLNK(metadata.st_mode):
            raise ContractError("tracked release file is a link or special object: %s" % relative)
        mode = b"755" if metadata.st_mode & stat.S_IXUSR else b"644"
        content_digest = bytes.fromhex(file_digest(path))
        digest.update(
            b"F\0"
            + relative.encode("utf-8")
            + b"\0"
            + mode
            + b"\0"
            + str(metadata.st_size).encode("ascii")
            + b"\0"
            + content_digest
        )
    return digest.hexdigest()


def _git(repo: Path, *args: str) -> str:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode:
        raise ContractError("git %s failed: %s" % (" ".join(args), proc.stderr.strip()))
    return proc.stdout.strip()


def _git_optional(repo: Path, *args: str) -> str | None:
    proc = subprocess.run(
        ["git", "-C", str(repo), *args],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    return proc.stdout.strip() if proc.returncode == 0 else None


def _resolved_public_ref(root: Path, ref: str) -> str:
    if ref in ("stable", "main"):
        candidates = ("refs/remotes/origin/%s" % ref, "refs/heads/%s" % ref, ref)
    elif re.fullmatch(r"v[0-9]+\.[0-9]+\.[0-9]+", ref):
        candidates = ("refs/tags/%s" % ref, ref)
    else:
        raise ContractError("release ref must be stable, main, or vX.Y.Z")
    for candidate in candidates:
        value = _git_optional(root, "rev-parse", "%s^{commit}" % candidate)
        if value and HEX40_RE.fullmatch(value):
            return candidate
    raise ContractError("release ref is unavailable: %s" % ref)


def _manifest_version(root: Path) -> str:
    versions = []
    for relative in (".claude-plugin/plugin.json", ".codex-plugin/plugin.json"):
        try:
            payload = json.loads((Path(root) / relative).read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ContractError("release manifest %s is unreadable: %s" % (relative, exc))
        version = payload.get("version")
        if not isinstance(version, str) or not VERSION_RE.fullmatch(version):
            raise ContractError("release manifest %s has no exact version" % relative)
        versions.append(version)
    if len(set(versions)) != 1:
        raise ContractError("client release manifests disagree")
    return versions[0]


def release_descriptor_from_checkout(
    root: Path,
    channel: str,
    ref: str,
    source_url: str,
    resolved_at: str | None = None,
) -> dict[str, Any]:
    root = Path(root)
    if channel not in ("stable", "edge", "pin"):
        raise ContractError("release channel must be stable, edge, or pin")
    validate_repository_url(source_url)
    git_ref = _resolved_public_ref(root, ref)
    commit = _git(root, "rev-parse", "%s^{commit}" % git_ref)
    if not HEX40_RE.fullmatch(commit):
        raise ContractError("resolved commit is invalid")
    head = _git(root, "rev-parse", "HEAD^{commit}")
    if head != commit:
        raise ContractError("checkout HEAD does not equal the resolved commit")
    if _git(root, "status", "--porcelain", "--untracked-files=all"):
        raise ContractError("release checkout must be clean")
    version = _manifest_version(root)
    tag_commit = _git(root, "rev-parse", "refs/tags/v%s^{commit}" % version)
    if tag_commit != commit:
        raise ContractError("exact release tag does not point at the resolved commit")
    tree = _git(root, "rev-parse", "%s^{tree}" % commit)
    if not HEX40_RE.fullmatch(tree):
        raise ContractError("resolved Git tree is invalid")
    tracked = set(filter(None, _git(root, "ls-files").splitlines()))
    modes = [line.split(None, 1)[0] for line in _git(root, "ls-tree", "-r", "HEAD").splitlines()]
    if any(mode not in ("100644", "100755") for mode in modes):
        raise ContractError("release Git tree contains a link or special object")
    descriptor = {
        "schema_version": 1,
        "version": version,
        "channel": channel,
        "ref": ref,
        "commit": commit,
        "tree": tree,
        "content_digest": canonical_tracked_tree_digest(root, tracked),
        "digest_algorithm": DIGEST_ALGORITHM,
        "tree_policy": TREE_POLICY,
        "source_url": source_url,
        "resolved_at": resolved_at or utcnow(),
    }
    return descriptor


def _validate_descriptor_shape(descriptor: Any) -> dict[str, Any]:
    descriptor = _require_mapping(descriptor, "release descriptor")
    required = {
        "schema_version",
        "version",
        "channel",
        "ref",
        "commit",
        "tree",
        "content_digest",
        "digest_algorithm",
        "tree_policy",
        "source_url",
        "resolved_at",
    }
    _reject_unknown(descriptor, required, "release descriptor")
    missing = sorted(required - set(descriptor))
    if missing:
        raise ContractError("release descriptor missing: %s" % ", ".join(missing))
    if descriptor.get("schema_version") != 1:
        raise ContractError("release descriptor schema_version must be 1")
    if not VERSION_RE.fullmatch(str(descriptor.get("version") or "")):
        raise ContractError("release descriptor version is invalid")
    if descriptor.get("channel") not in ("stable", "edge", "pin"):
        raise ContractError("release descriptor channel is invalid")
    expected_ref = {
        "stable": "stable",
        "edge": "main",
        "pin": "v%s" % descriptor.get("version"),
    }[descriptor["channel"]]
    if descriptor.get("ref") != expected_ref:
        raise ContractError("release descriptor ref does not match its channel")
    if not HEX40_RE.fullmatch(str(descriptor.get("commit") or "")):
        raise ContractError("release descriptor commit is invalid")
    if not HEX40_RE.fullmatch(str(descriptor.get("tree") or "")):
        raise ContractError("release descriptor tree is invalid")
    if not HEX64_RE.fullmatch(str(descriptor.get("content_digest") or "")):
        raise ContractError("release descriptor digest is invalid")
    if descriptor.get("digest_algorithm") != DIGEST_ALGORITHM:
        raise ContractError("release descriptor digest algorithm is invalid")
    if descriptor.get("tree_policy") != TREE_POLICY:
        raise ContractError("release descriptor tree policy is invalid")
    validate_repository_url(descriptor.get("source_url"))
    source = urlsplit(str(descriptor.get("source_url") or ""))
    if source.scheme != "https" or not source.hostname:
        raise ContractError("release descriptor source_url must use HTTPS")
    _parse_datetime(descriptor.get("resolved_at"), "release descriptor resolved_at")
    return descriptor


def validate_release_descriptor(descriptor: Any) -> dict[str, Any]:
    """Public closed-schema validator for release and active-pointer readers."""
    return _validate_descriptor_shape(descriptor)


def verify_release_checkout(root: Path, descriptor: Any) -> None:
    descriptor = _validate_descriptor_shape(descriptor)
    root = Path(root)
    if _git(root, "rev-parse", "HEAD^{commit}") != descriptor["commit"]:
        raise ContractError("release commit does not match the descriptor")
    if _git(root, "rev-parse", "HEAD^{tree}") != descriptor["tree"]:
        raise ContractError("release Git tree does not match the descriptor")
    if _git(root, "rev-parse", "refs/tags/v%s^{commit}" % descriptor["version"]) != descriptor["commit"]:
        raise ContractError("release tag does not match the descriptor")
    if _manifest_version(root) != descriptor["version"]:
        raise ContractError("release manifests do not match the descriptor")
    tracked = set(filter(None, _git(root, "ls-files").splitlines()))
    if canonical_tracked_tree_digest(root, tracked) != descriptor["content_digest"]:
        raise ContractError("release content digest does not match the descriptor")


def verify_materialized_release(root: Path, descriptor: Any) -> None:
    descriptor = _validate_descriptor_shape(descriptor)
    if _manifest_version(Path(root)) != descriptor["version"]:
        raise ContractError("materialized release manifests do not match the descriptor")
    observed = canonical_tree_digest(Path(root))
    if observed != descriptor["content_digest"]:
        raise ContractError("materialized release content digest does not match the descriptor")


def activate_cli(
    release_root: Path,
    descriptor: Any,
    launcher_path: Path,
    active_descriptor_path: Path,
) -> None:
    descriptor = _validate_descriptor_shape(descriptor)
    release_root = Path(release_root).resolve()
    verify_materialized_release(release_root, descriptor)
    cli = release_root / "skills" / "synthesis-onboarding" / "scripts" / "synthesis_cli.py"
    if not cli.is_file() or cli.is_symlink():
        raise ContractError("release has no trusted synthesis CLI")
    launcher_path = Path(launcher_path)
    active_descriptor_path = Path(active_descriptor_path)
    launcher = (
        "#!/bin/sh\n"
        + LAUNCHER_MARK
        + "\nset -eu\nexec python3 -B - "
        + shlex.quote(str(active_descriptor_path))
        + ' "$@" <<\'PY\'\n'
        + "import json, os, stat, sys\n"
        + "from pathlib import Path\n"
        + "descriptor_path = Path(sys.argv[1])\n"
        + "meta = descriptor_path.lstat()\n"
        + "if stat.S_ISLNK(meta.st_mode) or not stat.S_ISREG(meta.st_mode):\n"
        + "    raise SystemExit('Synthesis active release descriptor is unsafe')\n"
        + "descriptor = json.loads(descriptor_path.read_text(encoding='utf-8'))\n"
        + "root = Path(descriptor['release_root'])\n"
        + "root_meta = root.lstat()\n"
        + "if stat.S_ISLNK(root_meta.st_mode) or not stat.S_ISDIR(root_meta.st_mode):\n"
        + "    raise SystemExit('Synthesis active release root is unsafe')\n"
        + "cli = root / 'skills' / 'synthesis-onboarding' / 'scripts' / 'synthesis_cli.py'\n"
        + "cli_meta = cli.lstat()\n"
        + "if stat.S_ISLNK(cli_meta.st_mode) or not stat.S_ISREG(cli_meta.st_mode):\n"
        + "    raise SystemExit('Synthesis active CLI is unsafe')\n"
        + "os.environ['SYNTHESIS_ACTIVE_DESCRIPTOR'] = str(descriptor_path)\n"
        + "os.execv(sys.executable, [sys.executable, '-B', str(cli), *sys.argv[2:]])\n"
        + "PY\n"
    ).encode("utf-8")
    lock_path = active_descriptor_path.with_name(active_descriptor_path.name + ".lock")
    lock_path.parent.mkdir(parents=True, exist_ok=True)
    with lock_path.open("a+b") as activation_lock:
        fcntl.flock(activation_lock.fileno(), fcntl.LOCK_EX)
        if launcher_path.exists() or launcher_path.is_symlink():
            if launcher_path.is_symlink() or not launcher_path.is_file():
                raise ContractError("refusing to replace a user-owned synthesis launcher")
            try:
                current = launcher_path.read_bytes()
            except OSError as exc:
                raise ContractError("cannot inspect existing synthesis launcher: %s" % exc)
            if current != launcher:
                raise ContractError("refusing to replace a user-owned synthesis launcher")
        else:
            atomic_write_bytes(launcher_path, launcher, mode=0o755)
        # The launcher is release-independent and reads this descriptor on every
        # invocation.  Activation therefore has exactly one mutable pointer and
        # one atomic replace; a crash can leave either the old or new generation,
        # never a split descriptor/launcher pair.
        active = dict(descriptor)
        active["release_root"] = str(release_root)
        active["activated_at"] = utcnow()
        atomic_write_json(active_descriptor_path, active)
        fcntl.flock(activation_lock.fileno(), fcntl.LOCK_UN)


def default_desired_state(
    profile: str,
    clients: list[str],
    channel: str,
    version_pin: str | None = None,
    layers: dict[str, str] | None = None,
    organizations: list[dict[str, str]] | None = None,
    personal_workspace: str | None = None,
    personal_configuration: dict[str, Any] | None = None,
    enabled: bool = True,
) -> dict[str, Any]:
    if profile not in ("full", "skills-only"):
        raise ContractError("profile must be full or skills-only")
    if not isinstance(clients, list) or not clients or set(clients) - {"claude", "codex"}:
        raise ContractError("clients must contain claude and/or codex")
    if channel not in ("stable", "edge"):
        raise ContractError("channel must be stable or edge")
    if version_pin is not None and not VERSION_RE.fullmatch(version_pin):
        raise ContractError("version pin must be an exact X.Y.Z version")
    if personal_workspace is not None:
        safe_identifier(personal_workspace, "personal workspace")
    personal_configuration = validate_personal_configuration(personal_configuration)
    organization_entries = organizations or []
    if layers is None:
        selected = set(PROFILE_LAYERS[profile])
        if profile == "full" and organization_entries:
            selected.add("organization")
        layers = {
            layer_id: "selected" if layer_id in selected else "declined"
            for layer_id in LAYER_IDS
        }
    return {
        "schema_version": 1,
        "enabled": enabled,
        "profile": profile,
        "clients": sorted(set(clients)),
        "release": {"channel": channel, "version_pin": version_pin},
        "personal_workspace": personal_workspace,
        "personal_configuration": personal_configuration,
        "layers": dict(sorted(layers.items())),
        "organizations": organization_entries,
    }


def validate_desired_state(value: Any) -> dict[str, Any]:
    """Validate the complete persisted desired-state contract at runtime."""
    value = _require_mapping(value, "desired state")
    allowed = {
        "schema_version", "enabled", "profile", "clients", "release",
        "personal_workspace", "personal_configuration", "layers", "organizations",
    }
    required = {
        "schema_version", "enabled", "profile", "clients", "release",
        "personal_workspace", "personal_configuration", "layers", "organizations",
    }
    _reject_unknown(value, allowed, "desired state")
    missing = sorted(required - set(value))
    if missing:
        raise ContractError("desired state is missing keys: %s" % ", ".join(missing))
    if value.get("schema_version") != SCHEMA_VERSION:
        raise ContractError("desired state schema is unsupported")
    if not isinstance(value.get("enabled"), bool):
        raise ContractError("desired state enabled must be boolean")
    profile = value.get("profile")
    if profile not in {"full", "skills-only"}:
        raise ContractError("desired state profile is invalid")
    clients = value.get("clients")
    if (
        not isinstance(clients, list)
        or not clients
        or any(not isinstance(client, str) for client in clients)
        or len(clients) != len(set(clients))
        or set(clients) - {"claude", "codex"}
    ):
        raise ContractError("desired state clients are invalid")
    release = _require_mapping(value.get("release"), "desired state release")
    _reject_unknown(release, {"channel", "version_pin"}, "desired state release")
    if set(release) != {"channel", "version_pin"}:
        raise ContractError("desired state release is incomplete")
    if release.get("channel") not in {"stable", "edge"}:
        raise ContractError("desired state release channel is invalid")
    pin = release.get("version_pin")
    if pin is not None and (not isinstance(pin, str) or not VERSION_RE.fullmatch(pin)):
        raise ContractError("desired state release pin is invalid")
    workspace = value.get("personal_workspace")
    if workspace is not None:
        safe_identifier(workspace, "desired state personal workspace")
    configuration = validate_personal_configuration(
        value.get("personal_configuration")
    )
    if profile == "full" and (workspace is None or configuration is None):
        raise ContractError(
            "full desired state requires a personal workspace and configuration"
        )
    if profile == "skills-only" and configuration is not None:
        raise ContractError(
            "skills-only desired state cannot contain personal configuration"
        )
    layers = _require_mapping(value.get("layers"), "desired state layers")
    if any(
        not isinstance(name, str) or choice not in {"selected", "declined"}
        for name, choice in layers.items()
    ):
        raise ContractError("desired state layer choices are invalid")
    if set(layers) != set(LAYER_IDS):
        raise ContractError("desired state layers must contain the complete catalog")
    organizations = value.get("organizations")
    if not isinstance(organizations, list):
        raise ContractError("desired state organizations must be a list")
    if len(organizations) > 1:
        raise ContractError("desired state supports at most one organization")
    if profile == "skills-only" and organizations:
        raise ContractError("skills-only desired state cannot enroll an organization")
    selected_layers = set(PROFILE_LAYERS[profile])
    if profile == "full" and organizations:
        selected_layers.add("organization")
    expected_layers = {
        layer_id: "selected" if layer_id in selected_layers else "declined"
        for layer_id in LAYER_IDS
    }
    if layers != expected_layers:
        raise ContractError("desired state layers do not match the selected profile")
    for index, entry_value in enumerate(organizations):
        entry = _require_mapping(entry_value, "desired state organizations[%d]" % index)
        fields = {"repository", "manifest_path", "commit_policy", "commit"}
        _reject_unknown(entry, fields, "desired state organizations[%d]" % index)
        if set(entry) != fields:
            raise ContractError("desired state organizations[%d] is incomplete" % index)
        validate_repository_url(entry.get("repository"))
        if entry.get("manifest_path") != ".agents/onboarding.yaml":
            raise ContractError("desired state organization manifest path is invalid")
        if entry.get("commit_policy") not in {"floating", "pinned"}:
            raise ContractError("desired state organization commit policy is invalid")
        if not HEX40_RE.fullmatch(str(entry.get("commit") or "")):
            raise ContractError("desired state organization commit is invalid")
    return value


def validate_personal_configuration(value: Any) -> dict[str, Any] | None:
    if value is None:
        return None
    value = _require_mapping(value, "desired state personal configuration")
    fields = {
        "display_name", "working_relationship", "timezone", "tone",
        "avoid_phrases", "git_name", "git_email", "working_hours",
        "protected_hours", "personal_remote_patterns", "confidential_terms",
        "inbox_cleanup",
    }
    _reject_unknown(value, fields, "desired state personal configuration")
    missing = sorted(fields - set(value))
    if missing:
        raise ContractError(
            "desired state personal configuration is missing: %s"
            % ", ".join(missing)
        )
    for key in ("display_name", "working_relationship", "timezone", "git_name", "git_email"):
        if not isinstance(value.get(key), str):
            raise ContractError(
                "desired state personal configuration %s must be text" % key
            )
    if not value["working_relationship"].strip() or not value["timezone"].strip():
        raise ContractError(
            "desired state personal relationship and timezone must be non-empty"
        )
    if bool(value["git_name"]) != bool(value["git_email"]):
        raise ContractError(
            "desired state personal Git name and email must be provided together"
        )
    if value["git_email"] and (
        "@" not in value["git_email"]
        or any(char.isspace() for char in value["git_email"])
    ):
        raise ContractError("desired state personal Git email is invalid")
    for key in (
        "tone", "avoid_phrases", "protected_hours",
        "personal_remote_patterns", "confidential_terms",
    ):
        items = value.get(key)
        if not isinstance(items, list) or any(
            not isinstance(item, str) or not item.strip() for item in items
        ):
            raise ContractError(
                "desired state personal configuration %s is invalid" % key
            )
    if not value["tone"]:
        raise ContractError("desired state personal tone must not be empty")
    if value["working_hours"] is not None and not isinstance(
        value["working_hours"], dict
    ):
        raise ContractError("desired state personal working_hours must be an object or null")
    if not isinstance(value["inbox_cleanup"], bool):
        raise ContractError("desired state personal inbox_cleanup must be boolean")
    return value


def validate_machine_observation(value: Any) -> dict[str, Any]:
    """Validate the complete persisted observation contract at runtime."""
    value = _require_mapping(value, "machine observation")
    _reject_unknown(value, {"schema_version", "generation", "transactions"}, "machine observation")
    if set(value) != {"schema_version", "generation", "transactions"}:
        raise ContractError("machine observation is incomplete")
    generation = value.get("generation")
    if value.get("schema_version") != OBSERVATION_SCHEMA_VERSION:
        raise ContractError("machine observation schema is unsupported")
    if isinstance(generation, bool) or not isinstance(generation, int) or generation < 0:
        raise ContractError("machine observation generation is invalid")
    transactions = value.get("transactions")
    if not isinstance(transactions, list):
        raise ContractError("machine observation transactions must be a list")
    allowed = {
        "transaction_id", "generation", "previous_active_generation", "state",
        "command", "desired_digest", "committed_desired_digest", "release",
        *TRUTH_PLANES, "instruction_receipt", "details", "started_at",
        "finished_at", "error",
    }
    required = {"transaction_id", "generation", "state", "command", "desired_digest", "started_at"}
    for index, transaction_value in enumerate(transactions):
        label = "machine observation transactions[%d]" % index
        transaction = _require_mapping(transaction_value, label)
        _reject_unknown(transaction, allowed, label)
        missing = sorted(required - set(transaction))
        if missing:
            raise ContractError("%s is missing keys: %s" % (label, ", ".join(missing)))
        if not re.fullmatch(r"[0-9a-f]{32}", str(transaction.get("transaction_id") or "")):
            raise ContractError("%s transaction_id is invalid" % label)
        item_generation = transaction.get("generation")
        if isinstance(item_generation, bool) or not isinstance(item_generation, int) or item_generation < 1:
            raise ContractError("%s generation is invalid" % label)
        previous = transaction.get("previous_active_generation")
        if previous is not None and (
            isinstance(previous, bool) or not isinstance(previous, int) or previous < 1
        ):
            raise ContractError("%s previous generation is invalid" % label)
        if transaction.get("state") not in {"pending", "committed", "aborted"}:
            raise ContractError("%s state is invalid" % label)
        if transaction.get("command") not in TRANSACTION_COMMANDS:
            raise ContractError("%s command is invalid" % label)
        for field in ("desired_digest", "committed_desired_digest"):
            if field in transaction and not HEX64_RE.fullmatch(str(transaction.get(field) or "")):
                raise ContractError("%s %s is invalid" % (label, field))
        for field in TRUTH_PLANES + ("instruction_receipt", "details"):
            if field in transaction and not isinstance(transaction.get(field), dict):
                raise ContractError("%s %s must be an object" % (label, field))
        if "release" in transaction:
            validate_release_descriptor(transaction["release"])
        for field in ("started_at", "finished_at"):
            if field in transaction:
                _parse_datetime(transaction[field], "%s %s" % (label, field))
        if "error" in transaction and not isinstance(transaction.get("error"), str):
            raise ContractError("%s error must be text" % label)
    return value


class SystemState:
    """Locked desired state plus append-only transaction observations."""

    def __init__(self, home: Path | None = None):
        if home is None:
            home = Path(os.environ.get("SYNTHESIS_HOME", str(Path.home())))
            config_base = Path(os.environ.get("XDG_CONFIG_HOME", str(home / ".config")))
            state_base = Path(os.environ.get("XDG_STATE_HOME", str(home / ".local" / "state")))
        else:
            home = Path(home)
            config_base = home / ".config"
            state_base = home / ".local" / "state"
        self.home = Path(home)
        self.config_dir = config_base / "synthesis"
        self.state_dir = state_base / "synthesis"
        self.desired_path = self.config_dir / "system-state.json"
        self.observation_path = self.state_dir / "observations.json"
        self.lock_path = self.state_dir / "transaction.lock"
        self.invites_path = self.state_dir / "consumed-invites.json"
        self.legacy_receipts_path = self.home / ".synthesis" / "onboarding" / "receipts.json"

    @contextlib.contextmanager
    def locked(self) -> Iterator[None]:
        self.state_dir.mkdir(parents=True, exist_ok=True)
        with self.lock_path.open("a+b") as lock:
            fcntl.flock(lock.fileno(), fcntl.LOCK_EX)
            try:
                yield
            finally:
                fcntl.flock(lock.fileno(), fcntl.LOCK_UN)

    def read_desired(self) -> dict[str, Any] | None:
        try:
            value = json.loads(self.desired_path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return None
        except (OSError, ValueError) as exc:
            raise ContractError("desired state is unreadable: %s" % exc)
        return validate_desired_state(value)

    def read_observation(self) -> dict[str, Any]:
        try:
            value = json.loads(self.observation_path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            return {"schema_version": OBSERVATION_SCHEMA_VERSION, "generation": 0, "transactions": []}
        except (OSError, ValueError) as exc:
            raise ContractError("machine observation is unreadable: %s" % exc)
        return validate_machine_observation(value)

    def _save_observation(self, value: dict[str, Any]) -> None:
        validate_machine_observation(value)
        atomic_write_json(self.observation_path, value)

    def legacy_migration_input(self) -> dict[str, Any] | None:
        """Return bounded legacy metadata for the first authoritative generation.

        The legacy receipt remains an implementation aid for conffile-safe removal,
        but its contents never become desired or observed authority.  We retain a
        digest and non-path policy summary so migration is auditable without copying
        the legacy file's machine-specific inventory into the new state model.
        """
        path = self.legacy_receipts_path
        try:
            metadata = path.lstat()
        except FileNotFoundError:
            return None
        except OSError as exc:
            raise ContractError("legacy onboarding receipt cannot be inspected: %s" % exc)
        if stat.S_ISLNK(metadata.st_mode) or not stat.S_ISREG(metadata.st_mode):
            raise ContractError("legacy onboarding receipt must be a regular non-symlink file")
        if metadata.st_size > 4 * 1024 * 1024:
            raise ContractError("legacy onboarding receipt exceeds the migration size limit")
        try:
            value = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ContractError("legacy onboarding receipt is unreadable: %s" % exc)
        if not isinstance(value, dict):
            raise ContractError("legacy onboarding receipt must be an object")

        def choices(name: str) -> tuple[dict[str, str], bool]:
            source = value.get(name)
            if source is None:
                return {}, True
            if not isinstance(source, dict):
                return {}, False
            result: dict[str, str] = {}
            for key, entry in source.items():
                if not isinstance(key, str) or not isinstance(entry, dict):
                    return {}, False
                choice = entry.get("choice")
                if choice not in {"selected", "declined"}:
                    return {}, False
                result[key] = choice
            return dict(sorted(result.items())), True

        def inventory_count(name: str) -> tuple[int, bool]:
            source = value.get(name)
            if source is None:
                return 0, True
            if not isinstance(source, dict):
                return 0, False
            return len(source), True

        layer_choices, layer_choices_valid = choices("layer_choices")
        component_choices, component_choices_valid = choices("component_choices")
        generated_file_count, generated_files_valid = inventory_count("generated_files")
        adopted_repository_count, adopted_repositories_valid = inventory_count("adopted_repos")
        managed_json_entry_count, managed_json_entries_valid = inventory_count(
            "managed_json_entries"
        )
        managed_text_entry_count, managed_text_entries_valid = inventory_count(
            "managed_text_entries"
        )

        raw_profile = value.get("profile")
        profile_valid = raw_profile is None or raw_profile in {"full", "skills-only"}
        receipt_version = value.get("version")
        receipt_version_valid = (
            isinstance(receipt_version, int)
            and not isinstance(receipt_version, bool)
            and receipt_version in {1, 2}
        )

        raw_policy = value.get("plugin_policy")
        plugin_policy_valid = raw_policy is None
        plugin_policy = None
        if isinstance(raw_policy, dict) and not set(raw_policy) - {"channel", "version_pin"}:
            channel = raw_policy.get("channel") or "stable"
            version_pin = raw_policy.get("version_pin")
            plugin_policy_valid = (
                channel in {"stable", "edge"}
                and (
                    version_pin is None
                    or (
                        isinstance(version_pin, str)
                        and VERSION_RE.fullmatch(version_pin) is not None
                    )
                )
            )
            if plugin_policy_valid:
                plugin_policy = {"channel": channel, "version_pin": version_pin}

        runs = value.get("runs")
        runs_valid = runs is None or (
            isinstance(runs, list) and all(isinstance(entry, dict) for entry in runs)
        )
        organization_run_count = (
            sum(1 for entry in runs if entry.get("manifest"))
            if isinstance(runs, list) and runs_valid
            else 0
        )
        instruction_state_present = any(
            key in value
            for key in (
                "instruction_generation",
                "instruction_receipt",
                "kernel_source_sha256",
            )
        )
        known_fields = {
            "version",
            "profile",
            "personal_workspace",
            "plugin_policy",
            "layer_choices",
            "component_choices",
            "generated_files",
            "adopted_repos",
            "managed_json_entries",
            "managed_text_entries",
            "runs",
            "instruction_generation",
            "instruction_receipt",
            "kernel_source_sha256",
        }

        return {
            "sha256": file_digest(path),
            "receipt_version": receipt_version,
            "receipt_version_valid": receipt_version_valid,
            "profile": raw_profile if profile_valid else None,
            "profile_valid": profile_valid,
            "personal_workspace_present": value.get("personal_workspace") is not None,
            "plugin_policy": plugin_policy,
            "plugin_policy_valid": plugin_policy_valid,
            "layer_choices": layer_choices,
            "layer_choices_valid": layer_choices_valid,
            "component_choices": component_choices,
            "component_choices_valid": component_choices_valid,
            "generated_file_count": generated_file_count,
            "generated_files_valid": generated_files_valid,
            "adopted_repository_count": adopted_repository_count,
            "adopted_repositories_valid": adopted_repositories_valid,
            "managed_json_entry_count": managed_json_entry_count,
            "managed_json_entries_valid": managed_json_entries_valid,
            "managed_text_entry_count": managed_text_entry_count,
            "managed_text_entries_valid": managed_text_entries_valid,
            "organization_run_count": organization_run_count,
            "runs_valid": runs_valid,
            "instruction_state_present": instruction_state_present,
            "unknown_field_count": len(set(value) - known_fields),
        }

    def run_transaction(
        self,
        command: str,
        desired: dict[str, Any],
        operation: Callable[[dict[str, Any]], dict[str, Any] | None],
        *,
        rollback: Callable[[BaseException], None] | None = None,
        already_locked: bool = False,
    ) -> dict[str, Any]:
        if command not in TRANSACTION_COMMANDS:
            raise ContractError("unsupported transaction command: %s" % command)
        desired_digest = json_digest(desired)
        lock_context = contextlib.nullcontext() if already_locked else self.locked()
        with lock_context:
            observation = self.read_observation()
            changed_recovery = False
            for old in observation["transactions"]:
                if old.get("state") == "pending":
                    old["state"] = "aborted"
                    old["error"] = "interrupted before commit"
                    old["finished_at"] = utcnow()
                    changed_recovery = True
            if changed_recovery:
                self._save_observation(observation)
            generation = max(
                [int(observation.get("generation", 0))]
                + [int(item.get("generation", 0)) for item in observation["transactions"]]
            ) + 1
            transaction = {
                "transaction_id": uuid.uuid4().hex,
                "generation": generation,
                "previous_active_generation": (
                    int(observation.get("generation", 0)) or None
                ),
                "state": "pending",
                "command": command,
                "desired_digest": desired_digest,
                "started_at": utcnow(),
            }
            if not observation["transactions"] and not self.desired_path.exists():
                legacy = self.legacy_migration_input()
                if legacy is not None:
                    transaction["details"] = {"legacy_migration_input": legacy}
            observation["transactions"].append(transaction)
            self._save_observation(observation)
            old_desired = self.desired_path.read_bytes() if self.desired_path.exists() else None
            desired_written = False
            try:
                result = operation(transaction) or {}
                if not isinstance(result, dict):
                    raise ContractError("transaction operation must return a mapping")
                unknown = set(result) - set(TRUTH_PLANES) - {"release", "instruction_receipt", "details"}
                final_desired = result.pop("_desired", desired)
                unknown.discard("_desired")
                if unknown:
                    raise ContractError("transaction result has unknown planes: %s" % ", ".join(sorted(unknown)))
                if not isinstance(final_desired, dict):
                    raise ContractError("transaction final desired state must be a mapping")
                validate_desired_state(final_desired)
                if "details" in result and "details" in transaction:
                    details = dict(transaction["details"])
                    details.update(result["details"])
                    result = dict(result)
                    result["details"] = details
                transaction.update(result)
                transaction["committed_desired_digest"] = json_digest(final_desired)
                atomic_write_json(self.desired_path, final_desired)
                desired_written = True
                transaction["state"] = "committed"
                transaction["finished_at"] = utcnow()
                observation["generation"] = generation
                self._save_observation(observation)
                return dict(transaction)
            except BaseException as exc:
                rollback_error = None
                if rollback is not None:
                    try:
                        rollback(exc)
                    except BaseException as rollback_exc:
                        rollback_error = str(rollback_exc)
                if desired_written:
                    if old_desired is None:
                        try:
                            self.desired_path.unlink()
                        except FileNotFoundError:
                            pass
                    else:
                        atomic_write_bytes(self.desired_path, old_desired)
                transaction["state"] = "aborted"
                transaction["error"] = str(exc)
                if rollback is not None:
                    details = dict(transaction.get("details") or {})
                    details["rollback"] = {
                        "status": "failed" if rollback_error else "restored",
                        **({"error": rollback_error} if rollback_error else {}),
                    }
                    transaction["details"] = details
                transaction["finished_at"] = utcnow()
                self._save_observation(observation)
                if rollback_error:
                    raise ContractError(
                        "transaction failed and resource rollback failed: %s" % rollback_error
                    ) from exc
                raise

    def record_outcome(
        self, receipt: dict[str, Any], *, already_locked: bool = False
    ) -> dict[str, Any]:
        """Attach trusted outcome evidence to the active committed generation."""
        lock_context = contextlib.nullcontext() if already_locked else self.locked()
        with lock_context:
            observation = self.read_observation()
            committed = [
                item for item in observation["transactions"] if item.get("state") == "committed"
            ]
            if not committed:
                raise ContractError("no committed synthesis generation can own the outcome")
            transaction = committed[-1]
            live = transaction.get("live-loaded")
            if not isinstance(live, dict) or live.get("status") != "verified":
                raise ContractError(
                    "outcome verification requires a live-loaded selected-client generation"
                )
            transaction["outcome-verified"] = dict(receipt)
            transaction["outcome-verified"]["generation"] = transaction["generation"]
            transaction["outcome-verified"]["transaction_id"] = transaction["transaction_id"]
            transaction["outcome-verified"]["live_loaded_sha256"] = json_digest(live)
            self._save_observation(observation)
            return dict(transaction["outcome-verified"])

    def record_live_load(
        self,
        *,
        receipt: dict[str, Any],
    ) -> bool:
        """Attach genuine SessionStart evidence to its matching generation."""
        receipt = _require_mapping(receipt, "live-load receipt")
        client = receipt.get("client")
        session_id = receipt.get("session_id")
        plugin_version = receipt.get("plugin_version")
        plugin_root = receipt.get("plugin_root")
        recorded_at = receipt.get("recorded_at")
        if client not in {"claude", "codex"}:
            raise ContractError("live-load receipt client is unsupported")
        if receipt.get("receipt_schema") != 2 or receipt.get("hook_event_name") != "SessionStart":
            raise ContractError("live-load receipt is not a SessionStart event")
        if receipt.get("transcript_bound_at_record") is not True:
            raise ContractError("live-load receipt is not transcript-bound")
        if receipt.get("provenance_env") != "%s-transcript" % client:
            raise ContractError("live-load receipt client provenance is invalid")
        try:
            uuid.UUID(str(session_id))
            uuid.UUID(str(receipt.get("receipt_event_id")))
        except (ValueError, TypeError, AttributeError):
            raise ContractError("live-load receipt identifiers must be UUIDs")
        if not isinstance(plugin_version, str) or not VERSION_RE.fullmatch(plugin_version):
            raise ContractError("live-load receipt plugin version is invalid")
        if not isinstance(plugin_root, str) or not plugin_root:
            raise ContractError("live-load receipt is incomplete")
        observed_time = _parse_datetime(recorded_at, "live-load recorded_at")
        age = (datetime.now(timezone.utc) - observed_time).total_seconds()
        if age < -300 or age > 15 * 60:
            raise ContractError("live-load receipt is outside the SessionStart freshness window")
        root = Path(plugin_root)
        try:
            root_meta = root.lstat()
        except OSError as exc:
            raise ContractError("live-load plugin root is unavailable: %s" % exc)
        if stat.S_ISLNK(root_meta.st_mode) or not stat.S_ISDIR(root_meta.st_mode):
            raise ContractError("live-load plugin root must be a real directory")
        if root.resolve() != root:
            raise ContractError("live-load plugin root must be canonical")
        if _manifest_version(root) != plugin_version:
            raise ContractError("live-load plugin root does not match its version")
        hooks = root / "hooks" / "hooks.json"
        try:
            hooks_meta = hooks.lstat()
            hooks_payload = json.loads(hooks.read_text(encoding="utf-8"))
        except (OSError, ValueError) as exc:
            raise ContractError("live-load hook definition is unavailable: %s" % exc)
        if stat.S_ISLNK(hooks_meta.st_mode) or not stat.S_ISREG(hooks_meta.st_mode):
            raise ContractError("live-load hook definition must be a regular file")
        if "SessionStart" not in json.dumps(hooks_payload, sort_keys=True):
            raise ContractError("live-load hook definition has no SessionStart event")
        transcript_value = receipt.get("transcript_path")
        if not isinstance(transcript_value, str) or not transcript_value:
            raise ContractError("live-load receipt has no transcript path")
        transcript = Path(transcript_value).expanduser()
        try:
            transcript_meta = transcript.lstat()
        except OSError as exc:
            raise ContractError("live-load transcript is unavailable: %s" % exc)
        if stat.S_ISLNK(transcript_meta.st_mode) or not stat.S_ISREG(transcript_meta.st_mode):
            raise ContractError("live-load transcript must be a regular file")
        if transcript_meta.st_size > 64 * 1024 * 1024:
            raise ContractError("live-load transcript exceeds the verification size limit")
        try:
            transcript_text = transcript.read_text(encoding="utf-8", errors="replace")
        except OSError as exc:
            raise ContractError("live-load transcript is unreadable: %s" % exc)
        if str(session_id) not in transcript_text:
            raise ContractError("live-load transcript does not bind the session identifier")
        if not self.desired_path.is_file() or not self.observation_path.is_file():
            return False
        with self.locked():
            desired = self.read_desired()
            observation = self.read_observation()
            committed = [
                item for item in observation["transactions"]
                if item.get("state") == "committed"
            ]
            if desired is None or not committed:
                return False
            if not desired.get("enabled", True):
                return False
            transaction = committed[-1]
            release = transaction.get("release")
            if not isinstance(release, dict):
                resolved = transaction.get("resolved") or {}
                release = resolved.get("release") if isinstance(resolved, dict) else None
            if not isinstance(release, dict) or release.get("version") != plugin_version:
                return False
            release_digest = release.get("content_digest")
            provenance = transaction.get("source-provenance") or {}
            source_root_value = provenance.get("root") if isinstance(provenance, dict) else None
            if not isinstance(release_digest, str) or not HEX64_RE.fullmatch(release_digest):
                raise ContractError("live-load generation has no release content digest")
            if not isinstance(source_root_value, str) or not source_root_value:
                raise ContractError("live-load generation has no immutable source root")
            source_root = Path(source_root_value)
            source_files = {
                relative
                for relative, metadata, _path in _iter_tree(source_root)
                if stat.S_ISREG(metadata.st_mode)
            }
            if not source_files:
                raise ContractError("live-load generation has no release file inventory")
            if canonical_tracked_tree_digest(source_root, source_files) != release_digest:
                raise ContractError("live-load source root drifted from the release digest")
            plugin_digest = canonical_tracked_tree_digest(root, source_files)
            if plugin_digest != release_digest:
                raise ContractError("live-load plugin root does not match the release digest")
            current = transaction.get("live-loaded")
            receipts = dict(current.get("receipts") or {}) if isinstance(current, dict) else {}
            receipts[client] = {
                "client": client,
                "session_id": session_id,
                "plugin_version": plugin_version,
                "plugin_root": str(root),
                "plugin_root_sha256": plugin_digest,
                "receipt_event_id": receipt["receipt_event_id"],
                "transcript_sha256": file_digest(transcript),
                "recorded_at": recorded_at,
            }
            selected = desired.get("clients") or []
            complete = all(
                isinstance(receipts.get(name), dict)
                and receipts[name].get("plugin_version") == plugin_version
                for name in selected
            )
            transaction["live-loaded"] = {
                "status": "verified" if complete else "partial",
                "release_version": plugin_version,
                "receipts": receipts,
            }
            self._save_observation(observation)
            return True


def _parse_datetime(value: Any, label: str) -> datetime:
    if not isinstance(value, str):
        raise ContractError("%s must be an ISO 8601 timestamp" % label)
    try:
        parsed = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except ValueError:
        raise ContractError("%s must be an ISO 8601 timestamp" % label)
    if parsed.tzinfo is None:
        raise ContractError("%s must include a timezone" % label)
    return parsed.astimezone(timezone.utc)


def validate_invite(invite: Any, now: datetime | None = None) -> dict[str, Any]:
    invite = _require_mapping(invite, "invite")
    allowed = {
        "schema_version",
        "repository",
        "provider",
        "manifest_path",
        "nonce",
        "display_name",
        "auth_help_url",
        "issued_at",
        "expires_at",
        "repository_commit",
    }
    _reject_unknown(invite, allowed, "invite")
    required = {
        "schema_version", "repository", "provider", "manifest_path", "nonce",
        "issued_at", "expires_at",
    }
    missing = sorted(required - set(invite))
    if missing:
        raise ContractError("invite missing: %s" % ", ".join(missing))
    if invite.get("schema_version") != 1:
        raise ContractError("invite schema_version must be 1")
    validate_repository_url(invite.get("repository"))
    if invite.get("provider") not in ("github", "gitlab", "bitbucket", "generic"):
        raise ContractError("invite provider is unsupported")
    if invite.get("manifest_path") != ".agents/onboarding.yaml":
        raise ContractError("invite manifest_path must be .agents/onboarding.yaml")
    nonce = invite.get("nonce")
    if not isinstance(nonce, str) or not re.fullmatch(
        r"[A-Za-z0-9_-]{16,128}", nonce
    ):
        raise ContractError("invite nonce must be 16-128 URL-safe characters")
    if "auth_help_url" in invite:
        auth = urlsplit(str(invite["auth_help_url"]))
        if auth.scheme != "https" or not auth.hostname or auth.username or auth.password:
            raise ContractError("invite auth_help_url must be credential-free HTTPS")
    if "repository_commit" in invite and not HEX40_RE.fullmatch(str(invite["repository_commit"])):
        raise ContractError("invite repository_commit must be an exact commit")
    issued = _parse_datetime(invite.get("issued_at"), "invite.issued_at")
    expires = _parse_datetime(invite.get("expires_at"), "invite.expires_at")
    now = (now or datetime.now(timezone.utc)).astimezone(timezone.utc)
    if expires <= issued:
        raise ContractError("invite expiry must follow issue time")
    if (expires - issued).total_seconds() > 7 * 24 * 60 * 60:
        raise ContractError("invite lifetime must not exceed seven days")
    if now < issued:
        raise ContractError("invite is not valid yet")
    if now >= expires:
        raise ContractError("invite has expired")
    return invite


def consume_invite(
    invite: Any,
    state: SystemState,
    now: datetime | None = None,
    *,
    already_locked: bool = False,
) -> str:
    invite = validate_invite(invite, now=now)
    digest = json_digest(invite)

    def record() -> None:
        try:
            consumed = json.loads(state.invites_path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            consumed = {"schema_version": 1, "digests": {}}
        except (OSError, ValueError) as exc:
            raise ContractError("consumed-invite state is unreadable: %s" % exc)
        if digest in consumed.get("digests", {}):
            raise ContractError("invite already consumed")
        consumed.setdefault("digests", {})[digest] = {"consumed_at": utcnow()}
        atomic_write_json(state.invites_path, consumed)
    if already_locked:
        record()
    else:
        with state.locked():
            record()
    return digest


def _tracked_source(root: Path, relative: str) -> tuple[Path, str, str]:
    path = contained_path(root, relative, "instruction source")
    if not path.is_file() or path.is_symlink():
        raise ContractError("required instruction source is not a regular file: %s" % relative)
    proc = subprocess.run(
        ["git", "-C", str(root), "ls-files", "--error-unmatch", "--", relative],
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if proc.returncode:
        raise ContractError("instruction source is not Git-tracked: %s" % relative)
    commit = _git(root, "rev-parse", "HEAD^{commit}")
    return path, commit, file_digest(path)


def _restore_file(path: Path, previous: tuple[bool, bytes, int]) -> None:
    existed, content, mode = previous
    if existed:
        atomic_write_bytes(path, content, mode=mode)
    else:
        try:
            path.unlink()
        except FileNotFoundError:
            pass


def materialize_instruction_pair(
    graph: Any,
    source_roots: dict[str, Path],
    workspace: Path,
    generation: int,
    previous_receipt: dict[str, Any] | None = None,
    fail_after_first: bool = False,
) -> dict[str, Any]:
    graph = _require_mapping(graph, "instruction graph")
    _reject_unknown(graph, {"schema_version", "sources", "output", "claude_adapter"}, "instruction graph")
    if graph.get("schema_version") != 1:
        raise ContractError("instruction graph schema_version must be 1")
    if graph.get("output") != "AGENTS.md" or graph.get("claude_adapter") != "CLAUDE.md":
        raise ContractError("instruction graph outputs must be AGENTS.md and CLAUDE.md")
    sources = graph.get("sources")
    if not isinstance(sources, list) or not sources:
        raise ContractError("instruction graph needs at least one source")
    workspace = Path(workspace)
    if workspace.is_symlink():
        raise ContractError("workspace must not be a symbolic link")
    workspace.mkdir(parents=True, exist_ok=True)
    targets = [workspace / "AGENTS.md", workspace / "CLAUDE.md"]
    if any(target.is_symlink() for target in targets):
        raise DriftError("instruction output is a symbolic link")
    if previous_receipt:
        expected_outputs = previous_receipt.get("outputs") or {}
        for target in targets:
            expected = (expected_outputs.get(target.name) or {}).get("sha256")
            if expected is None or not target.is_file() or file_digest(target) != expected:
                raise DriftError("instruction output drift: %s" % target.name)

    parts = [
        "<!-- synthesis-instructions:generated -->",
        "# Workspace Instructions",
    ]
    source_receipts = []
    roles_seen = set()
    for index, entry in enumerate(sources):
        entry = _require_mapping(entry, "instruction sources[%d]" % index)
        _reject_unknown(entry, {"role", "path", "required"}, "instruction sources[%d]" % index)
        role = entry.get("role")
        if role not in ("public", "organization", "personal"):
            raise ContractError("instruction source role is unsupported")
        if role in roles_seen:
            raise ContractError("instruction graph contains duplicate role: %s" % role)
        roles_seen.add(role)
        relative = safe_relative_path(entry.get("path"), "instruction source path")
        root = source_roots.get(role)
        required = entry.get("required", True)
        if root is None:
            if required:
                raise ContractError("required instruction source root is missing: %s" % role)
            continue
        try:
            path, commit, digest = _tracked_source(Path(root), relative)
        except ContractError:
            if required:
                raise
            continue
        text = path.read_text(encoding="utf-8").strip()
        parts.extend(["", "## %s" % role.title(), "", text])
        source_receipts.append(
            {
                "role": role,
                "repository": str(Path(root).resolve()),
                "commit": commit,
                "path": relative,
                "sha256": digest,
            }
        )
    rendered = ("\n".join(parts).rstrip() + "\n").encode("utf-8")
    rendered_digest = hashlib.sha256(rendered).hexdigest()
    if previous_receipt:
        expected_outputs = previous_receipt.get("outputs") or {}
        if all(
            (expected_outputs.get(target.name) or {}).get("sha256") == rendered_digest
            for target in targets
        ):
            unchanged = dict(previous_receipt)
            unchanged["unchanged"] = True
            return unchanged
    previous = []
    for target in targets:
        previous.append(
            (
                target.exists(),
                target.read_bytes() if target.exists() else b"",
                stat.S_IMODE(target.stat().st_mode) if target.exists() else 0o644,
            )
        )
    temporary_paths = []
    try:
        for target in targets:
            with tempfile.NamedTemporaryFile(
                mode="wb", dir=workspace, prefix=target.name + ".", suffix=".stage", delete=False
            ) as temporary:
                temporary.write(rendered)
                temporary.flush()
                os.fsync(temporary.fileno())
                temporary_paths.append(Path(temporary.name))
        os.replace(temporary_paths[0], targets[0])
        if fail_after_first:
            raise ContractError("injected failure after first instruction activation")
        os.replace(temporary_paths[1], targets[1])
        _fsync_directory(workspace)
    except BaseException:
        _restore_file(targets[0], previous[0])
        _restore_file(targets[1], previous[1])
        raise
    finally:
        for temporary in temporary_paths:
            try:
                temporary.unlink()
            except FileNotFoundError:
                pass
    return {
        "schema_version": 1,
        "generation": generation,
        "sources": source_receipts,
        "outputs": {
            target.name: {"path": str(target), "sha256": rendered_digest} for target in targets
        },
        "materialized_at": utcnow(),
    }


def verify_outcome(task_id: str, evidence: Any, repo_root: Path) -> dict[str, Any]:
    capabilities = load_contract_documents(Path(repo_root))["capabilities"]
    declared = {
        item.get("id"): item
        for item in capabilities.get("public_acceptance_tasks", [])
        if isinstance(item, dict)
    }
    task = declared.get(task_id)
    if task is None:
        raise ContractError("outcome task is not trusted by this release")
    evidence = _require_mapping(evidence, "outcome evidence")
    if evidence.get("source_class") != task.get("source_class"):
        raise ContractError("outcome source class does not match the trusted capability")
    if task_id != "workspace-grounding-check":
        raise ContractError("outcome task has no public verifier")
    workspace_value = evidence.get("workspace")
    if not isinstance(workspace_value, str) or not workspace_value:
        raise ContractError("outcome evidence needs a workspace path")
    workspace = Path(workspace_value)
    if not workspace.is_dir() or workspace.is_symlink():
        raise ContractError("outcome workspace is unavailable")
    workspace = workspace.resolve()
    git_root = _git_optional(workspace, "rev-parse", "--show-toplevel")
    if not git_root or Path(git_root).resolve() != workspace:
        raise ContractError("outcome workspace must be a Git repository root")
    kb_config = workspace / ".agents" / "knowledge-base.yaml"
    if not kb_config.is_file() or kb_config.is_symlink():
        raise ContractError("workspace has no tracked knowledge-base declaration")
    config_relative = kb_config.relative_to(workspace).as_posix()
    if _git_optional(workspace, "ls-files", "--error-unmatch", "--", config_relative) is None:
        raise ContractError("knowledge-base declaration is not Git-tracked")
    if _git(workspace, "status", "--porcelain", "--", config_relative):
        raise ContractError("knowledge-base declaration has uncommitted changes")
    match = re.search(r"(?m)^bundle_path:\s*([^\s#]+)\s*$", kb_config.read_text(encoding="utf-8"))
    if not match:
        raise ContractError("knowledge-base declaration has no bundle_path")
    bundle = contained_path(workspace, match.group(1), "knowledge bundle")
    bundle_relative = bundle.relative_to(workspace).as_posix()
    tracked_text = _git(workspace, "ls-files", "--", bundle_relative)
    tracked = sorted(filter(None, tracked_text.splitlines()))
    files = []
    for relative in tracked:
        path = contained_path(workspace, relative, "tracked knowledge source")
        if not path.is_file() or path.is_symlink():
            raise ContractError("tracked knowledge source is not a regular file")
        files.append(path)
    if not files:
        raise ContractError("knowledge bundle contains no Git-tracked source file")
    if _git(workspace, "status", "--porcelain", "--", bundle_relative):
        raise ContractError("knowledge bundle has uncommitted source changes")
    digest = hashlib.sha256()
    for path in files:
        relative = path.relative_to(workspace).as_posix()
        digest.update(relative.encode("utf-8") + b"\0" + bytes.fromhex(file_digest(path)))
    return {
        "task_id": task_id,
        "capability": task["capability"],
        "source_class": task["source_class"],
        "workspace": str(workspace),
        "workspace_commit": _git(workspace, "rev-parse", "HEAD^{commit}"),
        "workspace_tree": _git(workspace, "rev-parse", "HEAD^{tree}"),
        "knowledge_config_sha256": file_digest(kb_config),
        "evidence_sha256": digest.hexdigest(),
        "evidence_count": len(files),
        "verified_at": utcnow(),
    }
