"""Validate explicit repository selection without calling bkt or reading context.

The grammar was captured from bkt's own --help; it is data, not authorization.
Unknown command/flag forms refuse with a diagnostic rather than guessing which
argument is a repository. Auth, context, help and identity reads stay separate.
"""
from __future__ import annotations
import re

COMMANDS = {'': {'aliases': [],
      'flags': {'--context': 'string',
                '--format': 'string',
                '--help': 'bool',
                '--jq': 'string',
                '--json': 'bool',
                '--template': 'string',
                '--version': 'bool',
                '--yaml': 'bool',
                '-c': 'string',
                '-h': 'bool',
                '-v': 'bool'}},
 'admin': {'aliases': [],
           'flags': {'--context': 'string',
                     '--format': 'string',
                     '--help': 'bool',
                     '--jq': 'string',
                     '--json': 'bool',
                     '--template': 'string',
                     '--yaml': 'bool',
                     '-c': 'string',
                     '-h': 'bool'}},
 'admin logging': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'admin logging get': {'aliases': [],
                       'flags': {'--context': 'string',
                                 '--format': 'string',
                                 '--help': 'bool',
                                 '--jq': 'string',
                                 '--json': 'bool',
                                 '--template': 'string',
                                 '--yaml': 'bool',
                                 '-c': 'string',
                                 '-h': 'bool'}},
 'admin logging set': {'aliases': [],
                       'flags': {'--async': 'bool',
                                 '--context': 'string',
                                 '--format': 'string',
                                 '--help': 'bool',
                                 '--jq': 'string',
                                 '--json': 'bool',
                                 '--level': 'string',
                                 '--template': 'string',
                                 '--yaml': 'bool',
                                 '-c': 'string',
                                 '-h': 'bool'}},
 'admin secrets': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'admin secrets rotate': {'aliases': [],
                          'flags': {'--context': 'string',
                                    '--format': 'string',
                                    '--help': 'bool',
                                    '--jq': 'string',
                                    '--json': 'bool',
                                    '--template': 'string',
                                    '--yaml': 'bool',
                                    '-c': 'string',
                                    '-h': 'bool'}},
 'api': {'aliases': [],
         'flags': {'--context': 'string',
                   '--field': 'stringArray',
                   '--format': 'string',
                   '--header': 'stringArray',
                   '--help': 'bool',
                   '--input': 'string',
                   '--jq': 'string',
                   '--json': 'bool',
                   '--method': 'string',
                   '--param': 'stringArray',
                   '--template': 'string',
                   '--yaml': 'bool',
                   '-F': 'stringArray',
                   '-H': 'stringArray',
                   '-P': 'stringArray',
                   '-X': 'string',
                   '-c': 'string',
                   '-d': 'string',
                   '-h': 'bool'}},
 'auth': {'aliases': [],
          'flags': {'--context': 'string',
                    '--format': 'string',
                    '--help': 'bool',
                    '--jq': 'string',
                    '--json': 'bool',
                    '--template': 'string',
                    '--yaml': 'bool',
                    '-c': 'string',
                    '-h': 'bool'}},
 'auth doctor': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--template': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'auth login': {'aliases': [],
                'flags': {'--allow-http': 'bool',
                          '--allow-insecure-store': 'bool',
                          '--auth-method': 'string',
                          '--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--kind': 'string',
                          '--template': 'string',
                          '--token': 'string',
                          '--username': 'string',
                          '--web': 'bool',
                          '--web-token': 'bool',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool',
                          '-w': 'bool'}},
 'auth logout': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--host': 'string',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--template': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'auth status': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--template': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'branch': {'aliases': [],
            'flags': {'--context': 'string',
                      '--format': 'string',
                      '--help': 'bool',
                      '--jq': 'string',
                      '--json': 'bool',
                      '--template': 'string',
                      '--yaml': 'bool',
                      '-c': 'string',
                      '-h': 'bool'}},
 'branch create': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--from': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--message': 'string',
                             '--project': 'string',
                             '--repo': 'string',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'branch delete': {'aliases': ['delete', 'rm'],
                   'flags': {'--context': 'string',
                             '--dry-run': 'bool',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--project': 'string',
                             '--repo': 'string',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'branch list': {'aliases': ['list', 'ls'],
                 'flags': {'--context': 'string',
                           '--filter': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--limit': 'int',
                           '--project': 'string',
                           '--repo': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'branch protect': {'aliases': [],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--template': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'branch protect add': {'aliases': [],
                        'flags': {'--context': 'string',
                                  '--format': 'string',
                                  '--group': 'strings',
                                  '--help': 'bool',
                                  '--jq': 'string',
                                  '--json': 'bool',
                                  '--project': 'string',
                                  '--repo': 'string',
                                  '--template': 'string',
                                  '--type': 'string',
                                  '--user': 'strings',
                                  '--yaml': 'bool',
                                  '-c': 'string',
                                  '-h': 'bool'}},
 'branch protect list': {'aliases': [],
                         'flags': {'--context': 'string',
                                   '--format': 'string',
                                   '--help': 'bool',
                                   '--jq': 'string',
                                   '--json': 'bool',
                                   '--project': 'string',
                                   '--repo': 'string',
                                   '--template': 'string',
                                   '--yaml': 'bool',
                                   '-c': 'string',
                                   '-h': 'bool'}},
 'branch protect remove': {'aliases': [],
                           'flags': {'--context': 'string',
                                     '--format': 'string',
                                     '--help': 'bool',
                                     '--jq': 'string',
                                     '--json': 'bool',
                                     '--project': 'string',
                                     '--repo': 'string',
                                     '--template': 'string',
                                     '--yaml': 'bool',
                                     '-c': 'string',
                                     '-h': 'bool'}},
 'branch rebase': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--interactive': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--no-fetch': 'bool',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'commit': {'aliases': [],
            'flags': {'--context': 'string',
                      '--format': 'string',
                      '--help': 'bool',
                      '--jq': 'string',
                      '--json': 'bool',
                      '--template': 'string',
                      '--yaml': 'bool',
                      '-c': 'string',
                      '-h': 'bool'}},
 'commit diff': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--project': 'string',
                           '--repo': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'completion': {'aliases': [],
                'flags': {'--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--template': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool'}},
 'completion bash': {'aliases': [],
                     'flags': {'--context': 'string',
                               '--format': 'string',
                               '--help': 'bool',
                               '--jq': 'string',
                               '--json': 'bool',
                               '--no-descriptions': 'bool',
                               '--template': 'string',
                               '--yaml': 'bool',
                               '-c': 'string',
                               '-h': 'bool'}},
 'completion fish': {'aliases': [],
                     'flags': {'--context': 'string',
                               '--format': 'string',
                               '--help': 'bool',
                               '--jq': 'string',
                               '--json': 'bool',
                               '--no-descriptions': 'bool',
                               '--template': 'string',
                               '--yaml': 'bool',
                               '-c': 'string',
                               '-h': 'bool'}},
 'completion powershell': {'aliases': [],
                           'flags': {'--context': 'string',
                                     '--format': 'string',
                                     '--help': 'bool',
                                     '--jq': 'string',
                                     '--json': 'bool',
                                     '--no-descriptions': 'bool',
                                     '--template': 'string',
                                     '--yaml': 'bool',
                                     '-c': 'string',
                                     '-h': 'bool'}},
 'completion zsh': {'aliases': [],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--no-descriptions': 'bool',
                              '--template': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'context': {'aliases': [],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--template': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'context create': {'aliases': [],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--host': 'string',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--project': 'string',
                              '--repo': 'string',
                              '--set-active': 'bool',
                              '--template': 'string',
                              '--workspace': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'context delete': {'aliases': ['delete', 'rm'],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--template': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'context list': {'aliases': ['list', 'ls'],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--template': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'context use': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--template': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'extension': {'aliases': [],
               'flags': {'--context': 'string',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--template': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'extension exec': {'aliases': [],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--template': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'extension install': {'aliases': [],
                       'flags': {'--context': 'string',
                                 '--format': 'string',
                                 '--help': 'bool',
                                 '--jq': 'string',
                                 '--json': 'bool',
                                 '--template': 'string',
                                 '--yaml': 'bool',
                                 '-c': 'string',
                                 '-h': 'bool'}},
 'extension list': {'aliases': ['list', 'ls'],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--template': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'extension remove': {'aliases': ['remove', 'rm'],
                      'flags': {'--context': 'string',
                                '--format': 'string',
                                '--help': 'bool',
                                '--jq': 'string',
                                '--json': 'bool',
                                '--template': 'string',
                                '--yaml': 'bool',
                                '-c': 'string',
                                '-h': 'bool'}},
 'help': {'aliases': [],
          'flags': {'--context': 'string',
                    '--format': 'string',
                    '--help': 'bool',
                    '--jq': 'string',
                    '--json': 'bool',
                    '--template': 'string',
                    '--yaml': 'bool',
                    '-c': 'string',
                    '-h': 'bool'}},
 'issue': {'aliases': [],
           'flags': {'--context': 'string',
                     '--format': 'string',
                     '--help': 'bool',
                     '--jq': 'string',
                     '--json': 'bool',
                     '--template': 'string',
                     '--yaml': 'bool',
                     '-c': 'string',
                     '-h': 'bool'}},
 'issue attachment': {'aliases': ['attachment', 'attach'],
                      'flags': {'--context': 'string',
                                '--format': 'string',
                                '--help': 'bool',
                                '--jq': 'string',
                                '--json': 'bool',
                                '--template': 'string',
                                '--yaml': 'bool',
                                '-c': 'string',
                                '-h': 'bool'}},
 'issue attachment delete': {'aliases': [],
                             'flags': {'--confirm': 'bool',
                                       '--context': 'string',
                                       '--format': 'string',
                                       '--help': 'bool',
                                       '--jq': 'string',
                                       '--json': 'bool',
                                       '--repo': 'string',
                                       '--template': 'string',
                                       '--workspace': 'string',
                                       '--yaml': 'bool',
                                       '-c': 'string',
                                       '-h': 'bool'}},
 'issue attachment download': {'aliases': [],
                               'flags': {'--all': 'bool',
                                         '--context': 'string',
                                         '--dir': 'string',
                                         '--format': 'string',
                                         '--help': 'bool',
                                         '--jq': 'string',
                                         '--json': 'bool',
                                         '--output': 'string',
                                         '--pattern': 'string',
                                         '--repo': 'string',
                                         '--skip-existing': 'bool',
                                         '--template': 'string',
                                         '--workspace': 'string',
                                         '--yaml': 'bool',
                                         '-c': 'string',
                                         '-h': 'bool'}},
 'issue attachment list': {'aliases': [],
                           'flags': {'--context': 'string',
                                     '--format': 'string',
                                     '--help': 'bool',
                                     '--jq': 'string',
                                     '--json': 'bool',
                                     '--repo': 'string',
                                     '--template': 'string',
                                     '--workspace': 'string',
                                     '--yaml': 'bool',
                                     '-c': 'string',
                                     '-h': 'bool'}},
 'issue attachment upload': {'aliases': [],
                             'flags': {'--context': 'string',
                                       '--format': 'string',
                                       '--help': 'bool',
                                       '--jq': 'string',
                                       '--json': 'bool',
                                       '--repo': 'string',
                                       '--template': 'string',
                                       '--workspace': 'string',
                                       '--yaml': 'bool',
                                       '-c': 'string',
                                       '-h': 'bool'}},
 'issue close': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--repo': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'issue comment': {'aliases': [],
                   'flags': {'--body': 'string',
                             '--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--list': 'bool',
                             '--repo': 'string',
                             '--template': 'string',
                             '--workspace': 'string',
                             '--yaml': 'bool',
                             '-b': 'string',
                             '-c': 'string',
                             '-h': 'bool'}},
 'issue create': {'aliases': [],
                  'flags': {'--assignee': 'string',
                            '--body': 'string',
                            '--component': 'string',
                            '--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--kind': 'string',
                            '--milestone': 'string',
                            '--priority': 'string',
                            '--repo': 'string',
                            '--template': 'string',
                            '--title': 'string',
                            '--version': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-a': 'string',
                            '-b': 'string',
                            '-c': 'string',
                            '-h': 'bool',
                            '-k': 'string',
                            '-p': 'string',
                            '-t': 'string'}},
 'issue delete': {'aliases': [],
                  'flags': {'--confirm': 'bool',
                            '--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--repo': 'string',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'issue edit': {'aliases': [],
                'flags': {'--assignee': 'string',
                          '--body': 'string',
                          '--component': 'string',
                          '--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--kind': 'string',
                          '--milestone': 'string',
                          '--priority': 'string',
                          '--repo': 'string',
                          '--state': 'string',
                          '--template': 'string',
                          '--title': 'string',
                          '--version': 'string',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-a': 'string',
                          '-b': 'string',
                          '-c': 'string',
                          '-h': 'bool',
                          '-k': 'string',
                          '-p': 'string',
                          '-s': 'string',
                          '-t': 'string'}},
 'issue list': {'aliases': ['list', 'ls'],
                'flags': {'--assignee': 'string',
                          '--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--kind': 'string',
                          '--limit': 'int',
                          '--milestone': 'string',
                          '--priority': 'string',
                          '--repo': 'string',
                          '--state': 'string',
                          '--template': 'string',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-L': 'int',
                          '-a': 'string',
                          '-c': 'string',
                          '-h': 'bool',
                          '-k': 'string',
                          '-p': 'string',
                          '-s': 'string'}},
 'issue reopen': {'aliases': [],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--repo': 'string',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'issue status': {'aliases': [],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--repo': 'string',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'issue view': {'aliases': [],
                'flags': {'--comments': 'bool',
                          '--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--repo': 'string',
                          '--template': 'string',
                          '--web': 'bool',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool',
                          '-w': 'bool'}},
 'mcp': {'aliases': [],
         'flags': {'--context': 'string',
                   '--format': 'string',
                   '--help': 'bool',
                   '--jq': 'string',
                   '--json': 'bool',
                   '--template': 'string',
                   '--yaml': 'bool',
                   '-c': 'string',
                   '-h': 'bool'}},
 'mcp serve': {'aliases': [],
               'flags': {'--context': 'string',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--template': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'perms': {'aliases': [],
           'flags': {'--context': 'string',
                     '--format': 'string',
                     '--help': 'bool',
                     '--jq': 'string',
                     '--json': 'bool',
                     '--template': 'string',
                     '--yaml': 'bool',
                     '-c': 'string',
                     '-h': 'bool'}},
 'perms project': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'perms project grant': {'aliases': [],
                         'flags': {'--context': 'string',
                                   '--format': 'string',
                                   '--help': 'bool',
                                   '--jq': 'string',
                                   '--json': 'bool',
                                   '--perm': 'string',
                                   '--project': 'string',
                                   '--template': 'string',
                                   '--user': 'string',
                                   '--yaml': 'bool',
                                   '-c': 'string',
                                   '-h': 'bool'}},
 'perms project list': {'aliases': [],
                        'flags': {'--context': 'string',
                                  '--format': 'string',
                                  '--help': 'bool',
                                  '--jq': 'string',
                                  '--json': 'bool',
                                  '--limit': 'int',
                                  '--project': 'string',
                                  '--template': 'string',
                                  '--yaml': 'bool',
                                  '-c': 'string',
                                  '-h': 'bool'}},
 'perms project revoke': {'aliases': [],
                          'flags': {'--context': 'string',
                                    '--format': 'string',
                                    '--help': 'bool',
                                    '--jq': 'string',
                                    '--json': 'bool',
                                    '--project': 'string',
                                    '--template': 'string',
                                    '--user': 'string',
                                    '--yaml': 'bool',
                                    '-c': 'string',
                                    '-h': 'bool'}},
 'perms repo': {'aliases': [],
                'flags': {'--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--template': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool'}},
 'perms repo grant': {'aliases': [],
                      'flags': {'--context': 'string',
                                '--format': 'string',
                                '--help': 'bool',
                                '--jq': 'string',
                                '--json': 'bool',
                                '--perm': 'string',
                                '--project': 'string',
                                '--repo': 'string',
                                '--template': 'string',
                                '--user': 'string',
                                '--yaml': 'bool',
                                '-c': 'string',
                                '-h': 'bool'}},
 'perms repo list': {'aliases': [],
                     'flags': {'--context': 'string',
                               '--format': 'string',
                               '--help': 'bool',
                               '--jq': 'string',
                               '--json': 'bool',
                               '--limit': 'int',
                               '--project': 'string',
                               '--repo': 'string',
                               '--template': 'string',
                               '--yaml': 'bool',
                               '-c': 'string',
                               '-h': 'bool'}},
 'perms repo revoke': {'aliases': [],
                       'flags': {'--context': 'string',
                                 '--format': 'string',
                                 '--help': 'bool',
                                 '--jq': 'string',
                                 '--json': 'bool',
                                 '--project': 'string',
                                 '--repo': 'string',
                                 '--template': 'string',
                                 '--user': 'string',
                                 '--yaml': 'bool',
                                 '-c': 'string',
                                 '-h': 'bool'}},
 'pipeline': {'aliases': [],
              'flags': {'--context': 'string',
                        '--format': 'string',
                        '--help': 'bool',
                        '--jq': 'string',
                        '--json': 'bool',
                        '--template': 'string',
                        '--yaml': 'bool',
                        '-c': 'string',
                        '-h': 'bool'}},
 'pipeline list': {'aliases': ['list', 'ls'],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--limit': 'int',
                             '--repo': 'string',
                             '--template': 'string',
                             '--workspace': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'pipeline logs': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--repo': 'string',
                             '--step': 'string',
                             '--template': 'string',
                             '--workspace': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'pipeline run': {'aliases': [],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--interval': 'duration',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--max-interval': 'duration',
                            '--ref': 'string',
                            '--repo': 'string',
                            '--template': 'string',
                            '--timeout': 'duration',
                            '--var': 'strings',
                            '--wait': 'bool',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'pipeline view': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--interval': 'duration',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--max-interval': 'duration',
                             '--repo': 'string',
                             '--template': 'string',
                             '--timeout': 'duration',
                             '--wait': 'bool',
                             '--workspace': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'pr': {'aliases': [],
        'flags': {'--context': 'string',
                  '--format': 'string',
                  '--help': 'bool',
                  '--jq': 'string',
                  '--json': 'bool',
                  '--template': 'string',
                  '--yaml': 'bool',
                  '-c': 'string',
                  '-h': 'bool'}},
 'pr approve': {'aliases': [],
                'flags': {'--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--project': 'string',
                          '--repo': 'string',
                          '--template': 'string',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool'}},
 'pr auto-merge': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'pr auto-merge disable': {'aliases': [],
                           'flags': {'--context': 'string',
                                     '--format': 'string',
                                     '--help': 'bool',
                                     '--jq': 'string',
                                     '--json': 'bool',
                                     '--project': 'string',
                                     '--repo': 'string',
                                     '--template': 'string',
                                     '--yaml': 'bool',
                                     '-c': 'string',
                                     '-h': 'bool'}},
 'pr auto-merge enable': {'aliases': [],
                          'flags': {'--close-source': 'bool',
                                    '--context': 'string',
                                    '--format': 'string',
                                    '--help': 'bool',
                                    '--jq': 'string',
                                    '--json': 'bool',
                                    '--message': 'string',
                                    '--project': 'string',
                                    '--repo': 'string',
                                    '--strategy': 'string',
                                    '--template': 'string',
                                    '--yaml': 'bool',
                                    '-c': 'string',
                                    '-h': 'bool'}},
 'pr auto-merge status': {'aliases': [],
                          'flags': {'--context': 'string',
                                    '--format': 'string',
                                    '--help': 'bool',
                                    '--jq': 'string',
                                    '--json': 'bool',
                                    '--project': 'string',
                                    '--repo': 'string',
                                    '--template': 'string',
                                    '--yaml': 'bool',
                                    '-c': 'string',
                                    '-h': 'bool'}},
 'pr checkout': {'aliases': [],
                 'flags': {'--branch': 'string',
                           '--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--project': 'string',
                           '--remote': 'string',
                           '--repo': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'pr checks': {'aliases': ['checks', 'builds'],
               'flags': {'--context': 'string',
                         '--fail-fast': 'bool',
                         '--format': 'string',
                         '--help': 'bool',
                         '--interval': 'duration',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--max-interval': 'duration',
                         '--project': 'string',
                         '--repo': 'string',
                         '--template': 'string',
                         '--timeout': 'duration',
                         '--wait': 'bool',
                         '--web': 'bool',
                         '--workspace': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'pr comment': {'aliases': [],
                'flags': {'--context': 'string',
                          '--file': 'string',
                          '--format': 'string',
                          '--from-line': 'int',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--parent': 'int',
                          '--pending': 'bool',
                          '--project': 'string',
                          '--repo': 'string',
                          '--template': 'string',
                          '--text': 'string',
                          '--to-line': 'int',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool'}},
 'pr comments': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--details': 'bool',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--project': 'string',
                           '--repo': 'string',
                           '--state': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'pr comments delete': {'aliases': ['delete', 'rm'],
                        'flags': {'--context': 'string',
                                  '--format': 'string',
                                  '--help': 'bool',
                                  '--jq': 'string',
                                  '--json': 'bool',
                                  '--project': 'string',
                                  '--repo': 'string',
                                  '--template': 'string',
                                  '--workspace': 'string',
                                  '--yaml': 'bool',
                                  '-c': 'string',
                                  '-h': 'bool'}},
 'pr comments reopen': {'aliases': [],
                        'flags': {'--context': 'string',
                                  '--format': 'string',
                                  '--help': 'bool',
                                  '--jq': 'string',
                                  '--json': 'bool',
                                  '--project': 'string',
                                  '--repo': 'string',
                                  '--template': 'string',
                                  '--workspace': 'string',
                                  '--yaml': 'bool',
                                  '-c': 'string',
                                  '-h': 'bool'}},
 'pr comments resolve': {'aliases': [],
                         'flags': {'--context': 'string',
                                   '--format': 'string',
                                   '--help': 'bool',
                                   '--jq': 'string',
                                   '--json': 'bool',
                                   '--project': 'string',
                                   '--repo': 'string',
                                   '--template': 'string',
                                   '--workspace': 'string',
                                   '--yaml': 'bool',
                                   '-c': 'string',
                                   '-h': 'bool'}},
 'pr create': {'aliases': [],
               'flags': {'--body': 'string',
                         '--close-source': 'bool',
                         '--context': 'string',
                         '--description': 'string',
                         '--destination': 'string',
                         '--draft': 'bool',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--project': 'string',
                         '--repo': 'string',
                         '--reviewer': 'strings',
                         '--source': 'string',
                         '--source-project': 'string',
                         '--source-repo': 'string',
                         '--target': 'string',
                         '--template': 'string',
                         '--title': 'string',
                         '--with-default-reviewers': 'bool',
                         '--workspace': 'string',
                         '--yaml': 'bool',
                         '-b': 'string',
                         '-c': 'string',
                         '-d': 'bool',
                         '-h': 'bool'}},
 'pr decline': {'aliases': ['decline', 'close'],
                'flags': {'--body': 'string',
                          '--comment': 'string',
                          '--context': 'string',
                          '--delete-source': 'bool',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--project': 'string',
                          '--repo': 'string',
                          '--template': 'string',
                          '--text': 'string',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool',
                          '-m': 'string'}},
 'pr diff': {'aliases': [],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--project': 'string',
                       '--repo': 'string',
                       '--stat': 'bool',
                       '--template': 'string',
                       '--workspace': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'pr edit': {'aliases': ['edit', 'update'],
             'flags': {'--body': 'string',
                       '--context': 'string',
                       '--description': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--project': 'string',
                       '--remove-reviewer': 'strings',
                       '--repo': 'string',
                       '--reviewer': 'strings',
                       '--template': 'string',
                       '--title': 'string',
                       '--with-default-reviewers': 'bool',
                       '--workspace': 'string',
                       '--yaml': 'bool',
                       '-b': 'string',
                       '-c': 'string',
                       '-h': 'bool',
                       '-t': 'string'}},
 'pr list': {'aliases': ['list', 'ls'],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--limit': 'int',
                       '--mine': 'bool',
                       '--project': 'string',
                       '--repo': 'string',
                       '--reviewer': 'bool',
                       '--state': 'string',
                       '--template': 'string',
                       '--workspace': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'pr merge': {'aliases': [],
              'flags': {'--close-source': 'bool',
                        '--context': 'string',
                        '--format': 'string',
                        '--help': 'bool',
                        '--jq': 'string',
                        '--json': 'bool',
                        '--message': 'string',
                        '--project': 'string',
                        '--repo': 'string',
                        '--strategy': 'string',
                        '--template': 'string',
                        '--workspace': 'string',
                        '--yaml': 'bool',
                        '-c': 'string',
                        '-h': 'bool'}},
 'pr publish': {'aliases': ['publish', 'ready'],
                'flags': {'--context': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--project': 'string',
                          '--repo': 'string',
                          '--template': 'string',
                          '--undo': 'bool',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool'}},
 'pr reaction': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--template': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'pr reaction add': {'aliases': [],
                     'flags': {'--context': 'string',
                               '--emoji': 'string',
                               '--format': 'string',
                               '--help': 'bool',
                               '--jq': 'string',
                               '--json': 'bool',
                               '--project': 'string',
                               '--repo': 'string',
                               '--template': 'string',
                               '--yaml': 'bool',
                               '-c': 'string',
                               '-h': 'bool'}},
 'pr reaction list': {'aliases': [],
                      'flags': {'--context': 'string',
                                '--format': 'string',
                                '--help': 'bool',
                                '--jq': 'string',
                                '--json': 'bool',
                                '--project': 'string',
                                '--repo': 'string',
                                '--template': 'string',
                                '--yaml': 'bool',
                                '-c': 'string',
                                '-h': 'bool'}},
 'pr reaction remove': {'aliases': [],
                        'flags': {'--context': 'string',
                                  '--emoji': 'string',
                                  '--format': 'string',
                                  '--help': 'bool',
                                  '--jq': 'string',
                                  '--json': 'bool',
                                  '--project': 'string',
                                  '--repo': 'string',
                                  '--template': 'string',
                                  '--yaml': 'bool',
                                  '-c': 'string',
                                  '-h': 'bool'}},
 'pr reopen': {'aliases': [],
               'flags': {'--context': 'string',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--project': 'string',
                         '--repo': 'string',
                         '--template': 'string',
                         '--workspace': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'pr suggestion': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--preview': 'bool',
                             '--project': 'string',
                             '--repo': 'string',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'pr task': {'aliases': [],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--template': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'pr task complete': {'aliases': [],
                      'flags': {'--context': 'string',
                                '--format': 'string',
                                '--help': 'bool',
                                '--jq': 'string',
                                '--json': 'bool',
                                '--project': 'string',
                                '--repo': 'string',
                                '--template': 'string',
                                '--workspace': 'string',
                                '--yaml': 'bool',
                                '-c': 'string',
                                '-h': 'bool'}},
 'pr task create': {'aliases': [],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--project': 'string',
                              '--repo': 'string',
                              '--template': 'string',
                              '--text': 'string',
                              '--workspace': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'pr task list': {'aliases': [],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--project': 'string',
                            '--repo': 'string',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'pr task reopen': {'aliases': [],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--project': 'string',
                              '--repo': 'string',
                              '--template': 'string',
                              '--workspace': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'pr view': {'aliases': [],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--project': 'string',
                       '--repo': 'string',
                       '--template': 'string',
                       '--web': 'bool',
                       '--workspace': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'project': {'aliases': [],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--template': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'project list': {'aliases': ['list', 'ls'],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--host': 'string',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--limit': 'int',
                            '--template': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'repo': {'aliases': [],
          'flags': {'--context': 'string',
                    '--format': 'string',
                    '--help': 'bool',
                    '--jq': 'string',
                    '--json': 'bool',
                    '--template': 'string',
                    '--yaml': 'bool',
                    '-c': 'string',
                    '-h': 'bool'}},
 'repo browse': {'aliases': [],
                 'flags': {'--context': 'string',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--project': 'string',
                           '--repo': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'repo clone': {'aliases': [],
                'flags': {'--context': 'string',
                          '--dest': 'string',
                          '--format': 'string',
                          '--help': 'bool',
                          '--jq': 'string',
                          '--json': 'bool',
                          '--project': 'string',
                          '--ssh': 'bool',
                          '--template': 'string',
                          '--workspace': 'string',
                          '--yaml': 'bool',
                          '-c': 'string',
                          '-h': 'bool'}},
 'repo create': {'aliases': [],
                 'flags': {'--cloud-project': 'string',
                           '--context': 'string',
                           '--default-branch': 'string',
                           '--description': 'string',
                           '--forkable': 'bool',
                           '--format': 'string',
                           '--help': 'bool',
                           '--jq': 'string',
                           '--json': 'bool',
                           '--project': 'string',
                           '--public': 'bool',
                           '--scm': 'string',
                           '--template': 'string',
                           '--workspace': 'string',
                           '--yaml': 'bool',
                           '-c': 'string',
                           '-h': 'bool'}},
 'repo list': {'aliases': ['list', 'ls'],
               'flags': {'--context': 'string',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--limit': 'int',
                         '--project': 'string',
                         '--template': 'string',
                         '--workspace': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'repo view': {'aliases': [],
               'flags': {'--context': 'string',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--project': 'string',
                         '--repo': 'string',
                         '--template': 'string',
                         '--workspace': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'status': {'aliases': [],
            'flags': {'--context': 'string',
                      '--format': 'string',
                      '--help': 'bool',
                      '--jq': 'string',
                      '--json': 'bool',
                      '--template': 'string',
                      '--yaml': 'bool',
                      '-c': 'string',
                      '-h': 'bool'}},
 'status commit': {'aliases': [],
                   'flags': {'--context': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--template': 'string',
                             '--yaml': 'bool',
                             '-c': 'string',
                             '-h': 'bool'}},
 'status pipeline': {'aliases': [],
                     'flags': {'--context': 'string',
                               '--format': 'string',
                               '--help': 'bool',
                               '--jq': 'string',
                               '--json': 'bool',
                               '--repo': 'string',
                               '--template': 'string',
                               '--workspace': 'string',
                               '--yaml': 'bool',
                               '-c': 'string',
                               '-h': 'bool'}},
 'status pr': {'aliases': [],
               'flags': {'--context': 'string',
                         '--format': 'string',
                         '--help': 'bool',
                         '--jq': 'string',
                         '--json': 'bool',
                         '--project': 'string',
                         '--repo': 'string',
                         '--template': 'string',
                         '--yaml': 'bool',
                         '-c': 'string',
                         '-h': 'bool'}},
 'status rate-limit': {'aliases': [],
                       'flags': {'--context': 'string',
                                 '--format': 'string',
                                 '--help': 'bool',
                                 '--jq': 'string',
                                 '--json': 'bool',
                                 '--template': 'string',
                                 '--yaml': 'bool',
                                 '-c': 'string',
                                 '-h': 'bool'}},
 'variable': {'aliases': [],
              'flags': {'--context': 'string',
                        '--format': 'string',
                        '--help': 'bool',
                        '--jq': 'string',
                        '--json': 'bool',
                        '--template': 'string',
                        '--yaml': 'bool',
                        '-c': 'string',
                        '-h': 'bool'}},
 'variable delete': {'aliases': ['delete', 'rm'],
                     'flags': {'--context': 'string',
                               '--deployment': 'string',
                               '--format': 'string',
                               '--help': 'bool',
                               '--jq': 'string',
                               '--json': 'bool',
                               '--repo': 'string',
                               '--scope': 'string',
                               '--template': 'string',
                               '--workspace': 'string',
                               '--yaml': 'bool',
                               '--yes': 'bool',
                               '-R': 'string',
                               '-c': 'string',
                               '-e': 'string',
                               '-h': 'bool',
                               '-y': 'bool'}},
 'variable get': {'aliases': [],
                  'flags': {'--context': 'string',
                            '--deployment': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--repo': 'string',
                            '--scope': 'string',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-R': 'string',
                            '-c': 'string',
                            '-e': 'string',
                            '-h': 'bool'}},
 'variable list': {'aliases': ['list', 'ls'],
                   'flags': {'--context': 'string',
                             '--deployment': 'string',
                             '--format': 'string',
                             '--help': 'bool',
                             '--jq': 'string',
                             '--json': 'bool',
                             '--limit': 'int',
                             '--repo': 'string',
                             '--scope': 'string',
                             '--template': 'string',
                             '--workspace': 'string',
                             '--yaml': 'bool',
                             '-L': 'int',
                             '-R': 'string',
                             '-c': 'string',
                             '-e': 'string',
                             '-h': 'bool'}},
 'variable set': {'aliases': [],
                  'flags': {'--body': 'string',
                            '--context': 'string',
                            '--deployment': 'string',
                            '--env-file': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--repo': 'string',
                            '--scope': 'string',
                            '--secured': 'bool',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-R': 'string',
                            '-b': 'string',
                            '-c': 'string',
                            '-e': 'string',
                            '-f': 'string',
                            '-h': 'bool',
                            '-s': 'bool'}},
 'webhook': {'aliases': [],
             'flags': {'--context': 'string',
                       '--format': 'string',
                       '--help': 'bool',
                       '--jq': 'string',
                       '--json': 'bool',
                       '--template': 'string',
                       '--yaml': 'bool',
                       '-c': 'string',
                       '-h': 'bool'}},
 'webhook create': {'aliases': [],
                    'flags': {'--active': 'bool',
                              '--context': 'string',
                              '--event': 'strings',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--name': 'string',
                              '--project': 'string',
                              '--repo': 'string',
                              '--template': 'string',
                              '--url': 'string',
                              '--workspace': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'webhook delete': {'aliases': ['delete', 'rm'],
                    'flags': {'--context': 'string',
                              '--format': 'string',
                              '--help': 'bool',
                              '--jq': 'string',
                              '--json': 'bool',
                              '--project': 'string',
                              '--repo': 'string',
                              '--template': 'string',
                              '--workspace': 'string',
                              '--yaml': 'bool',
                              '-c': 'string',
                              '-h': 'bool'}},
 'webhook list': {'aliases': ['list', 'ls'],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--project': 'string',
                            '--repo': 'string',
                            '--template': 'string',
                            '--workspace': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}},
 'webhook test': {'aliases': [],
                  'flags': {'--context': 'string',
                            '--format': 'string',
                            '--help': 'bool',
                            '--jq': 'string',
                            '--json': 'bool',
                            '--project': 'string',
                            '--repo': 'string',
                            '--template': 'string',
                            '--yaml': 'bool',
                            '-c': 'string',
                            '-h': 'bool'}}}


class BindingError(ValueError):
    pass


def _parse(argv, profile):
    positional, flags = [], {}
    index = 0
    while index < len(argv):
        token = argv[index]
        if token == "--":
            positional.extend(argv[index + 1:])
            break
        if token.startswith("-"):
            name, eq, value = token.partition("=")
            if name not in profile:
                return None
            if profile[name] == "bool":
                if eq and value not in {"true", "false"}:
                    return None
                value = value if eq else "true"
            elif not eq:
                index += 1
                if index >= len(argv):
                    return None
                value = argv[index]
            flags.setdefault(name, []).append(value)
        else:
            positional.append(token)
        index += 1
    return positional, flags


def _slug(value):
    return isinstance(value, str) and re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]*", value) and value not in {".", ".."}


def validate_argv(argv):
    """Return target evidence only; never approve a command or contact a service."""
    if not argv or argv[0].rsplit("/", 1)[-1] != "bkt":
        raise BindingError("repository binding expects a literal bkt executable")
    matches = []
    for path, contract in COMMANDS.items():
        result = _parse(argv[1:], contract["flags"])
        if result is None:
            continue
        positional, flags = result
        names = path.split()
        aliases = contract["aliases"] or names[-1:]
        if names and (len(positional) < len(names) or positional[:len(names)-1] != names[:-1]
                      or positional[len(names)-1] not in aliases):
            continue
        if not names and positional:
            continue
        has_children = any(key.startswith(path + " ") for key in COMMANDS) if path else True
        help_requested = flags.get("--help") == ["true"] or flags.get("-h") == ["true"]
        if has_children and not help_requested and path not in {"", "help"}:
            continue
        matches.append((len(names), path, positional[len(names):], flags, contract))
    if not matches:
        raise BindingError("bkt repository binding cannot parse this command/flag form; inspect bkt --help and use a supported explicit --repo command")
    _, path, operands, flags, contract = max(matches, key=lambda item: item[0])
    if flags.get("--help") == ["true"] or flags.get("-h") == ["true"] or (
            not path and (flags.get("--version") == ["true"] or flags.get("-v") == ["true"])):
        return {"scope": "help"}
    if path.split()[:1] in (["auth"], ["context"], ["completion"], ["help"]):
        return {"scope": "non-repository"}
    if path == "api":
        if len(operands) != 1:
            raise BindingError("bkt api needs one explicit repository API path")
        endpoint = operands[0]
        if endpoint == "/user" and not any(k in flags for k in ("--field", "-F", "--input", "-d")) and all(
                value.upper() == "GET" for key in ("--method", "-X") for value in flags.get(key, [])):
            return {"scope": "identity-read"}
        # bkt api has no --repo flag: the exact canonical path is the binding.
        parts = endpoint.split("/")
        selected = None
        if len(parts) >= 4 and parts[:2] == ["", "repositories"]:
            selected = parts[2:4]
        elif len(parts) >= 8 and parts[:5] == ["", "rest", "api", "1.0", "projects"] and parts[6] == "repos":
            selected = [parts[5], parts[7]]
        if (selected is None or not all(_slug(value) for value in selected)
                or any(part in {".", ".."} for part in parts) or any(c in endpoint for c in "%$`\\?#")):
            raise BindingError("bkt api requires a literal canonical repository path; a mutable context is not repository evidence")
        return {"scope": "repository", "namespace": selected[0], "repo": selected[1], "binding": "api-path"}
    if "--repo" not in contract["flags"]:
        raise BindingError("this bkt operation has no verified explicit repository binding; use a repository-specific command")
    repos = flags.get("--repo", []) + flags.get("-R", [])
    if len(repos) != 1 or not _slug(repos[0]):
        raise BindingError("bkt repository operation requires exactly one literal --repo <slug>; shared context cannot select it")
    for key in ("--workspace", "--project"):
        values = flags.get(key, [])
        if len(values) > 1 or any(not _slug(value) for value in values):
            raise BindingError("bkt repository namespace must be one literal value")
    return {"scope": "repository", "repo": repos[0], "binding": "--repo"}
