"""The packet generator: reader contract, refusals, page bytes, review material and filing.

Edge cases E42 to E54 of the v5 evaluation carry their number in the test name. Browser
behaviour is asserted here on the generated bytes; test_packet_browser.py drives a real
page when a Chromium is present.
"""
from __future__ import annotations

import base64
import hashlib
import json
import re
import socket
import subprocess
import sys
import urllib.request
import zlib
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS))
import build_packet as bp  # noqa: E402

DOCTOR_MARKER = re.compile(r"<!-- synthesis-decision-packet spec-sha256:([0-9a-f]{64}) -->")
DOCTOR_SPEC = re.compile(r'<script type="application/json" id="spec">(.*?)</script>', re.S)


def spec(n=5, **over):
    """A reader-compliant synthetic packet."""
    s = {
        "title": "Synthetic release choices",
        "audience": "A fixture principal who has not read the review.",
        "options": [{"value": "ship", "label": "Ship the fix this week", "tone": "ok"},
                    {"value": "hold", "label": "Leave the code as it stands", "tone": "warn"}],
        "rows": [{"id": f"R-{i}", "label": f"Synthetic finding {i}", "context": "Fixture only.",
                  "impact": {"accept": "The fixture changes.", "decline": "The fixture stays."},
                  "recommendation": "ship"} for i in range(1, n + 1)],
    }
    s.update(over)
    return s


def hard(problems):
    return [p for p in problems if not p.startswith(("NOTE:", "READER:"))]


def cli(*args, stdin=None):
    return subprocess.run([sys.executable, str(SCRIPTS / "build_packet.py"), *map(str, args)],
                          input=stdin, capture_output=True, text=True)


def write(tmp_path, value, name="spec.json"):
    path = tmp_path / name
    path.write_text(json.dumps(value, ensure_ascii=False), encoding="utf-8")
    return path


def png(width=2, height=2):
    """A valid PNG; a large declared size gets a token pixel stream, enough for header checks."""
    def chunk(kind, data):
        return len(data).to_bytes(4, "big") + kind + data + zlib.crc32(kind + data).to_bytes(4, "big")
    header = width.to_bytes(4, "big") + height.to_bytes(4, "big") + b"\x08\x02\x00\x00\x00"
    rows = height if width * height <= 64 else 1
    pixels = zlib.compress(b"".join(b"\x00" + b"\xff\x00\x00" * min(width, 8) for _ in range(rows)))
    return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", header) + chunk(b"IDAT", pixels) + chunk(b"IEND", b"")


def text_asset(aid, kind, text):
    return {"id": aid, "title": f"Synthetic {kind}", "kind": kind,
            "content": {"text": text, "sha256": hashlib.sha256(text.encode("utf-8")).hexdigest()}}


def image_asset(data, aid="screenshot"):
    return {"id": aid, "title": "Synthetic screenshot", "kind": "image", "filename": "screenshot.png",
            "description": "A two-pixel synthetic image.",
            "content": {"base64": base64.b64encode(data).decode("ascii"), "sha256": hashlib.sha256(data).hexdigest(),
                        "size": len(data), "media_type": "image/png"}}


def review_row(assets):
    return {"revision": "draft-1", "review_assets": assets,
            "delivery": {"format": "Plain text email", "destinations": ["To: reader@example.test"], "attachments": []}}


# --- page bytes -------------------------------------------------------------------------

def test_e54_charset_is_declared_in_the_first_bytes_and_typography_survives(tmp_path):
    """Without the charset first, curly quotes and dashes render as mojibake over a plain
    local HTTP server; the defect reached a real packet and was found by loading the page."""
    curly = "Don’t “converge” first — surface it…"
    current = spec()
    current["rows"][0]["label"] = curly
    page = bp.build(current)
    head = page[:200]
    assert '<meta charset="utf-8">' in head and head.index("<meta charset") < head.index("<title")
    path = tmp_path / "p.html"
    path.write_bytes(page.encode("utf-8"))
    embedded = json.loads(DOCTOR_SPEC.search(path.read_bytes().decode("utf-8")).group(1))
    assert embedded["rows"][0]["label"] == curly


def test_marker_pins_the_embedded_spec_in_the_form_the_context_doctor_reads():
    page = bp.build(spec())
    marker, embedded = DOCTOR_MARKER.search(page), DOCTOR_SPEC.search(page)
    assert marker and embedded
    assert hashlib.sha256(embedded.group(1).encode("utf-8")).hexdigest() == marker.group(1)
    assert page.index(marker.group(0)) < page.index("<style>")


def test_e42_a_fresh_packet_selects_nothing_and_marks_the_recommendation_on_its_control():
    """Pressed state comes from saved choices alone; the recommendation only marks a button.
    A packet that opens decided cannot tell "I agreed" from "I never looked"."""
    page = bp.build(spec())
    assert 'b.setAttribute("aria-pressed", String(b.dataset.value === d))' in page
    body = page.split("<body", 1)[1].split("<script", 1)[0]
    assert 'aria-pressed="true"' not in body
    block = page[page.index("if (row.recommendation === o.value)"):]
    block = block[:block.index("b.addEventListener")]
    assert 'b.dataset.recommended = "true";' in block and "aria-pressed" not in block
    assert 'button[data-recommended="true"]' in page and '"recommended: "' in page


def test_e47_copy_selects_first_reports_synchronously_and_reports_on_every_path():
    """navigator.clipboard is blocked in a sandboxed artifact iframe; in the origin run the
    button did nothing and said nothing. Select first, say something at once, then try."""
    page = bp.build(spec())
    fn = page[page.index("function copySummary"):page.index('document.getElementById("copy").addEventListener')]
    order = [fn.index("ta.select()"), fn.index('status.textContent = "Selected'),
             fn.index("document.execCommand"), fn.index("navigator.clipboard")]
    assert order == sorted(order)
    assert "setTimeout(blocked, 2000)" in fn, "an unsettled clipboard promise must still end in a report"
    assert fn.count("status.textContent") >= 3 and "the text is selected" in fn


def test_e48_spec_text_cannot_close_the_script_block():
    current = spec()
    current["rows"][0]["context"] = "literal </script><script>window.injected=true</script>"
    current["rows"][1]["context"] = "literal <!--<script> sequence"
    page = bp.build(current)
    payload = DOCTOR_SPEC.search(page).group(1)
    assert "<" not in payload
    assert page.count("</script>") == 2
    assert json.loads(payload) == {**current, "storage_key": bp.slugify(current["title"]), "filters": []}


def test_page_is_self_contained():
    page = bp.build(spec())
    assert not re.search(r'<(script|img|link|iframe)[^>]+(src|href)="(https?:)?//', page)
    assert "fetch(" not in page and "XMLHttpRequest" not in page


def test_each_button_carries_its_consequence_and_the_row_shows_impact_both_ways():
    current = spec()
    current["rows"][0]["options"] = [
        {"value": "ship", "label": "Ship the fix this week", "consequence": "The release waits a day."},
        {"value": "hold", "label": "Leave the code as it stands", "consequence": "The bug ships."}]
    page = bp.build(current)
    assert "if (o.consequence) return o.consequence;" in page
    assert "row.recommendation === o.value ? row.impact.accept : row.impact.decline" in page
    assert "If you take the recommendation:" in page
    assert not hard(bp.validate(current))


# --- refusals ---------------------------------------------------------------------------

@pytest.mark.parametrize("labels", [("Yes", "No"), ("Approve", "Reject"), ("Yes, do that", "No thanks"),
                                    ("Accept it", "Decline"), ("Do that", "Stop"), ("OK", "Cancel")])
def test_e43_bare_labels_are_refused_under_strict_reader_with_the_accepted_form(tmp_path, labels):
    """Measured 2026-09-14: rows offering "Yes, do that" / "No" collected notes instead of
    decisions because the principal could not tell what each button would do."""
    current = spec()
    current["rows"][2]["options"] = [{"value": "a", "label": labels[0]}, {"value": "b", "label": labels[1]}]
    current["rows"][2]["recommendation"] = "a"
    findings = [p for p in bp.validate(current) if p.startswith("READER:")]
    assert findings and "R-3" in findings[0] and repr(labels[0]) in findings[0]
    path = write(tmp_path, current)
    refused = cli(path, "--strict-reader", "-o", tmp_path / "p.html")
    assert refused.returncode == 2 and not (tmp_path / "p.html").exists()
    assert bp.ACCEPTED_LABEL_FORM in refused.stderr and "--strict-reader" in refused.stderr
    assert cli(path, "-o", tmp_path / "p.html").returncode == 0  # a warning without strictness


def test_labels_sharing_every_content_word_raise_a_reader_finding():
    current = spec(options=[{"value": "keep", "label": "Keep it"}, {"value": "keep2", "label": "Keep that"}])
    for row in current["rows"]:
        row["recommendation"] = "keep"
    assert any("bare" in p or "content word" in p for p in bp.validate(current) if p.startswith("READER:"))
    current["options"][1]["label"] = "Keep them on my phone"
    current["options"][0]["label"] = "Take them off my phone"
    assert not [p for p in bp.validate(current) if p.startswith("READER:")]


def test_reader_contract_findings_warn_by_default_and_refuse_under_strict_reader(tmp_path):
    current = spec()
    del current["audience"]
    del current["rows"][0]["impact"]
    reader = [p for p in bp.validate(current) if p.startswith("READER:")]
    assert len(reader) == 2 and "R-1" in reader[1]
    path = write(tmp_path, current)
    assert cli(path, "--strict-reader", "--stdout").returncode == 2
    assert cli(path, "--stdout").returncode == 0


def test_e44_ids_that_collide_after_browser_coercion_are_refused(tmp_path):
    """JSON 1 and "1" become the same browser storage key."""
    current = spec()
    current["rows"][0]["id"], current["rows"][1]["id"] = 1, "1"
    assert any("must be a non-empty string" in p for p in bp.validate(current))
    result = cli(write(tmp_path, current), "-o", tmp_path / "p.html")
    assert result.returncode == 2 and not (tmp_path / "p.html").exists()


@pytest.mark.parametrize("bad", [" R-1", "R-1 ", "R  1", "", True, "R-2"])
def test_ids_with_edge_or_doubled_whitespace_blank_or_duplicate_are_refused(bad):
    current = spec()
    current["rows"][0]["id"] = bad
    assert hard(bp.validate(current))


@pytest.mark.parametrize("field", ["title", "row label", "option label", "id"])
def test_e49_a_line_break_in_title_label_or_id_is_refused(field):
    """The paste is one line per field; a packet that builds must also file."""
    current = spec()
    if field == "title":
        current["title"] = "Two\nlines"
    elif field == "row label":
        current["rows"][0]["label"] = "Two\r\nlines"
    elif field == "option label":
        current["options"][0]["label"] = "Ship the fix\nthis week"
    else:
        current["rows"][0]["id"] = "R\n1"
    assert any("line break" in p for p in hard(bp.validate(current)))


def test_e53_fewer_than_five_rows_is_flagged_and_needs_allow_small(tmp_path):
    current = spec(n=3)
    assert any(p.startswith("NOTE: only 3 rows") for p in bp.validate(current))
    path = write(tmp_path, current)
    refused = cli(path, "--strict-reader", "--stdout")
    assert refused.returncode == 2 and "--allow-small" in refused.stderr
    assert cli(path, "--strict-reader", "--allow-small", "--stdout").returncode == 0


@pytest.mark.parametrize("change, expected", [
    (lambda s: s.update(options=[{"value": "only", "label": "Keep them on my phone"}]), "at least two options"),
    (lambda s: s["options"][1].update(value="ship"), "used by more than one option"),
    (lambda s: s["options"][0].update(value=1), "must be a non-empty string"),
    (lambda s: s["options"][0].update(tone="loud"), "tone"),
    (lambda s: s["rows"][0].update(recommendation="publish"), "is not one of its options"),
    (lambda s: [r.pop("recommendation") for r in s["rows"]], "questionnaire"),
    (lambda s: s["rows"][0].update(impact={"accept": "x"}), "impact needs both"),
    (lambda s: s["rows"][0].update(disagreement={"a": {"who": "A", "view": "x"}}), "disagreement needs both"),
    (lambda s: s["rows"][0].update(links=[{"label": "x", "href": "javascript:alert(1)"}]), "scheme"),
    (lambda s: s["rows"][0].update(prior_position={"statement": "x"}), "prior_position"),
    (lambda s: s.update(glossary=[{"term": "holdout"}]), "glossary"),
    (lambda s: s["rows"][0].update(severity="urgent"), "severity"),
])
def test_malformed_specs_are_refused_before_anything_is_written(change, expected):
    current = spec()
    change(current)
    assert any(expected in p for p in hard(bp.validate(current))), bp.validate(current)


def test_strict_json_refuses_duplicate_keys_and_nonfinite_numbers(tmp_path):
    for raw in ('{"title": "a", "title": "b"}', '{"title": NaN}'):
        path = tmp_path / "bad.json"
        path.write_text(raw, encoding="utf-8")
        result = cli(path, "--stdout")
        assert result.returncode == 2 and "cannot read valid spec JSON" in result.stderr


# --- review material --------------------------------------------------------------------

def test_e52_review_material_is_embedded_and_nothing_is_fetched(monkeypatch):
    """An image, a code excerpt and a draft email are shown inside the packet; an
    unavailable item keeps its link but nothing is fetched, at build time or by the page."""
    def no_network(*_args, **_kwargs):
        raise AssertionError("the generator must not touch the network")
    monkeypatch.setattr(socket, "socket", no_network)
    monkeypatch.setattr(urllib.request, "urlopen", no_network)
    email = "To: reader@example.test\nSubject: Synthetic draft\n\nHello, fixture."
    current = spec()
    current["rows"][0].update(review_row([text_asset("draft", "correspondence", email),
                                          text_asset("excerpt", "code", "def fixture():\n    return 1\n"),
                                          image_asset(png())]))
    current["rows"][1].update(review_row([{"id": "missing", "title": "Remote file", "kind": "document",
                                           "description": "Not supplied.",
                                           "content": {"unavailable": "Not supplied to the agent",
                                                       "source": "https://example.invalid/file.pdf"}}]))
    assert not hard(bp.validate(current))
    page = bp.build(current)
    embedded = json.loads(DOCTOR_SPEC.search(page).group(1))
    assert embedded["rows"][0]["review_assets"][0]["content"]["text"] == email
    assert embedded["rows"][0]["review_assets"][2]["content"]["base64"] == base64.b64encode(png()).decode()
    assert "media.src = 'data:' + content.media_type" in page and "No content was fetched." in page
    assert bp.review_assets_ready(current["rows"][0]) and not bp.review_assets_ready(current["rows"][1])
    assert "b.disabled = !assetsReady(row);" in page


@pytest.mark.parametrize("mutate", [
    lambda a: a["content"].update(sha256="0" * 64),
    lambda a: a["content"].update(base64="not base64!"),
    lambda a: a["content"].update(media_type="image/gif"),
    lambda a: a.update(filename="../screenshot.png"),
    lambda a: a.pop("description"),
    lambda a: a.update(kind="executable"),
    lambda a: a["content"].update(base64=base64.b64encode(png(9000, 9000)).decode(),
                                  size=len(png(9000, 9000)), sha256=hashlib.sha256(png(9000, 9000)).hexdigest()),
    lambda a: a.update(content={"unavailable": "missing", "source": "file:///etc/hosts"}),
])
def test_review_material_refusals(mutate):
    current = spec()
    asset = image_asset(png())
    mutate(asset)
    current["rows"][0].update(review_row([asset]))
    assert hard(bp.validate(current))


def test_review_material_requires_its_revision_and_delivery_envelope():
    current = spec()
    current["rows"][0].update(review_row([text_asset("draft", "plain_text", "Synthetic.")]))
    del current["rows"][0]["delivery"]
    assert any("delivery" in p for p in hard(bp.validate(current)))
    current = spec()
    current["rows"][0]["revision"] = "draft-1"
    assert any("requires review_assets" in p for p in hard(bp.validate(current)))


# --- outputs and filing -----------------------------------------------------------------

def test_schema_prints_the_spec_format():
    result = cli("--schema")
    assert result.returncode == 0 and "Decision-packet spec (JSON)" in result.stdout
    assert '"carried_from"' in result.stdout and "review_assets" in result.stdout


def test_stdout_and_out_write_the_page(tmp_path):
    path = write(tmp_path, spec())
    printed = cli(path, "--stdout")
    assert printed.returncode == 0 and printed.stdout.startswith("<!doctype html>")
    out = tmp_path / "work" / "packet.html"
    assert cli(path, "-o", out).returncode == 0 and out.read_text(encoding="utf-8") == printed.stdout
    write(tmp_path, spec(title="Revised synthetic choices"))
    assert cli(path, "-o", out).returncode == 0 and "Revised synthetic choices" in out.read_text(encoding="utf-8")


def test_file_into_files_dated_spec_and_page_and_keeps_earlier_versions(tmp_path):
    artifacts = tmp_path / "resources" / "artifacts"
    artifacts.mkdir(parents=True)
    path = write(tmp_path, spec())
    first = cli(path, "--strict-reader", "--file-into", artifacts, "--date", "2026-09-14")
    assert first.returncode == 0, first.stderr
    stem = artifacts / "2026-09-14-synthetic-release-choices"
    spec_copy, page_copy = Path(f"{stem}-spec.json"), Path(f"{stem}.html")
    assert spec_copy.read_bytes() == bp.canonical_spec_bytes(spec())
    assert DOCTOR_MARKER.search(page_copy.read_text(encoding="utf-8"))
    assert cli(path, "--file-into", artifacts, "--date", "2026-09-14").returncode == 0  # identical: idempotent
    assert len(list(artifacts.iterdir())) == 2
    revised = spec()
    revised["rows"][0]["context"] = "Revised fixture."
    write(tmp_path, revised)
    assert cli(path, "--file-into", artifacts, "--date", "2026-09-14").returncode == 0
    assert len(list(artifacts.iterdir())) == 4 and spec_copy.read_bytes() == bp.canonical_spec_bytes(spec())


def test_file_into_needs_an_existing_directory_and_date_needs_file_into(tmp_path):
    path = write(tmp_path, spec())
    missing = cli(path, "--file-into", tmp_path / "nowhere")
    assert missing.returncode == 2 and "not an existing directory" in missing.stderr
    assert cli(path, "--stdout", "--date", "2026-09-14").returncode == 2
    (tmp_path / "a").mkdir()
    assert cli(path, "--file-into", tmp_path / "a", "--date", "2026-02-30").returncode == 2
