"""The generated page driven in a real headless Chromium: E42, E45, E47 and E48 as behaviour.

Set SYNTHESIS_TEST_CHROMIUM to a chrome-headless-shell executable, or put one on PATH (else
chromium, chromium-browser or google-chrome). Full Chrome's headless mode never finished
--dump-dom on this page in testing (2026-10-06, Chrome on macOS and Linux CI), while the
headless shell, Chrome's build for automation, returns in a fraction of a second, so CI
installs the shell. Without a browser these tests skip, except where CI requires one;
test_packet_build.py asserts the same properties on the generated bytes.
The page is loaded from a local file with a throwaway profile; nothing touches the network.
"""
from __future__ import annotations

import html
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import pytest

SCRIPTS = Path(__file__).resolve().parents[1] / "scripts"
sys.path.insert(0, str(SCRIPTS))
import build_packet as bp  # noqa: E402
import record_rulings as rr  # noqa: E402


def find_chromium():
    configured = os.environ.get("SYNTHESIS_TEST_CHROMIUM")
    if configured:
        return configured if Path(configured).is_file() else None
    return next(filter(None, (shutil.which(n) for n in
                              ("chrome-headless-shell", "chromium", "chromium-browser", "google-chrome"))), None)


CHROMIUM = find_chromium()
if CHROMIUM is None and os.environ.get("SYNTHESIS_REQUIRE_CHROMIUM") == "1":  # CI: a missing browser fails
    raise RuntimeError("SYNTHESIS_REQUIRE_CHROMIUM=1 but no Chromium was found")
pytestmark = pytest.mark.skipif(CHROMIUM is None, reason="no Chromium: set SYNTHESIS_TEST_CHROMIUM or put one on PATH")

PRELUDE = """<script>
window.packetErrors = [];
window.addEventListener('error', function (e) { packetErrors.push(e.message); });
</script>"""
BLOCK_STORAGE = """<script>
Object.defineProperty(window, 'localStorage', {configurable: true,
  get: function () { throw new DOMException('blocked for the fixture', 'SecurityError'); }});
</script>"""
DRIVER = """<script>
(function () {
  var out = {errors: window.packetErrors, injected: window.injected === true};
  function rows() { return Array.from(document.querySelectorAll('.row')); }
  function buttons(r) { return Array.from(r.querySelectorAll('.opts button')); }
  out.fresh = rows().map(function (r) {
    return {pressed: buttons(r).map(function (b) { return b.getAttribute('aria-pressed'); }),
            recommended: buttons(r).map(function (b) { return b.dataset.recommended === 'true'; })};
  });
  document.getElementById('copy').click();
  out.copyStatus = document.getElementById('copystatus').textContent;
  buttons(rows()[0])[1].click();
  var note = rows()[0].querySelector('.note textarea');
  note.value = 'Synthetic browser note';
  note.dispatchEvent(new Event('input', {bubbles: true}));
  window.confirm = function () { return true; };
  document.getElementById('bulk').click();
  out.summary = document.getElementById('summary').value;
  var pre = document.createElement('pre');
  pre.id = 'packet-browser-result';
  pre.textContent = JSON.stringify(out);
  document.body.appendChild(pre);
})();
</script>"""


def spec():
    return {
        "title": "Synthetic browser packet", "audience": "Fixture principal",
        "options": [{"value": "ship", "label": "Ship the fixture"},
                    {"value": "hold", "label": "Keep the fixture as it is"}],
        "rows": [{"id": f"W-{i}", "label": f"Synthetic row {i}", "context": "Fixture only.",
                  "impact": {"accept": "The fixture ships.", "decline": "The fixture stays."},
                  "recommendation": "ship"} for i in range(5)],
    }


def drive(current, block_storage):
    page = bp.build(current)
    prelude = PRELUDE + (BLOCK_STORAGE if block_storage else "")
    page = page.replace('<script type="application/json"', prelude + '<script type="application/json"', 1)
    page = page.replace("</body>", DRIVER + "</body>", 1)
    # Chromium's socket path limit is short, so the profile lives in a short temporary folder.
    work = Path(tempfile.mkdtemp(prefix="packet-browser-", dir="/tmp"))
    try:
        probe = work / "probe.html"
        probe.write_text(page, encoding="utf-8")
        env = dict(os.environ, TMPDIR=str(work))
        result = subprocess.run([CHROMIUM, "--headless", "--disable-gpu", "--no-first-run",
                                 "--no-default-browser-check", "--disable-extensions",
                                 "--disable-background-networking", f"--user-data-dir={work / 'profile'}",
                                 "--dump-dom", probe.as_uri()], capture_output=True, text=True, timeout=60, env=env)
    finally:
        shutil.rmtree(work, ignore_errors=True)
    assert result.returncode == 0, result.stderr[-2000:]
    found = re.search(r'<pre id="packet-browser-result">(.*?)</pre>', result.stdout, re.S)
    assert found, "the page did not reach its driver"
    return json.loads(html.unescape(found.group(1)))


def awkward(current):
    """Ids a plain object or a CSS selector would mishandle, and spec text that tries to end the script."""
    for row, rid in zip(current["rows"], ("__proto__", "constructor", "Q\f0", "hasOwnProperty")):
        row["id"] = rid
    current["rows"][4]["context"] = "literal </script><script>window.injected=true</script> <!--<script>"
    return current


@pytest.mark.parametrize("block_storage, change", [(False, None), (True, None), (False, awkward)],
                         ids=["storage", "storage-blocked", "awkward-ids-and-script-text"])
def test_e42_e45_e47_e48_the_real_page(block_storage, change):
    current = change(spec()) if change else spec()
    seen = drive(current, block_storage)
    assert seen["errors"] == [] and seen["injected"] is False  # E48: spec text stayed text
    # E42: nothing pressed when the page opens; the recommended option is marked on its control.
    assert all(row["pressed"] == ["false", "false"] for row in seen["fresh"])
    assert all(row["recommended"] == [True, False] for row in seen["fresh"])
    # E47: the copy control reports at once, whichever copy path the browser allows.
    assert seen["copyStatus"].strip()
    # E45 and E46: the paste alone records every decision, says so when storage was blocked,
    # and labels the bulk acceptances.
    parsed = rr.parse_summary(seen["summary"], current)
    assert parsed["decided"] == 5
    assert parsed["rulings"][0]["choice_value"] == "hold" and parsed["rulings"][0]["note"] == "Synthetic browser note"
    assert [r["accepted_in_bulk"] for r in parsed["rulings"]] == [False, True, True, True, True]
    if block_storage:
        assert rr.STORAGE_TRAILER in seen["summary"] and '"storage_blocked":true' in seen["summary"]
