"""Load the release-owned pure-Python PyYAML bytes without site packages."""
from __future__ import annotations

import hashlib
import importlib
import importlib.abc
import importlib.util
import json
from pathlib import Path
import stat
import sys
import uuid


MANIFEST_SHA256 = "2a165696e79bb9c0251cd5ad63f425163a964c1563c0462b5db96dd203d62cf0"
PAYLOAD = Path(__file__).resolve().parent.parent / "vendor/pyyaml"


class DependencyError(ValueError):
    """The release-owned dependency cannot be verified."""


def _regular(path):
    if not path.is_absolute() or ".." in path.parts:
        raise DependencyError("dependency path must be absolute without traversal")
    if any(item.is_symlink() for item in (path, *path.parents)):
        raise DependencyError("dependency path crosses a symlink")
    if not path.is_file() or not stat.S_ISREG(path.stat().st_mode):
        raise DependencyError("dependency file is missing or not regular: " + path.name)


def verified_bytes(root):
    """Return the checked bytes used for execution, never reopen after checking."""
    root = Path(root)
    manifest_path = root / "manifest.json"
    _regular(manifest_path)
    if manifest_path.stat().st_mode & 0o111:
        raise DependencyError("dependency manifest has an unexpected executable mode")
    manifest_bytes = manifest_path.read_bytes()
    if hashlib.sha256(manifest_bytes).hexdigest() != MANIFEST_SHA256:
        raise DependencyError("release-owned PyYAML manifest differs from the release pin")
    manifest = json.loads(manifest_bytes)
    expected = manifest["files"]
    observed = set()
    for path in root.rglob("*"):
        if path.is_symlink():
            raise DependencyError("dependency payload contains a symlink")
        relative = path.relative_to(root)
        if path.is_dir():
            if relative.as_posix() not in {"yaml", "yaml/__pycache__"}:
                raise DependencyError("dependency payload has an unknown directory")
            continue
        # Standard compileall residue is not imported; immutable release checks
        # also exclude generated bytecode from their source-content identity.
        if relative.parent.as_posix() == "yaml/__pycache__" and path.suffix == ".pyc":
            _regular(path)
            continue
        observed.add(relative.as_posix())
    if observed != set(expected) | {"manifest.json"}:
        raise DependencyError("dependency payload membership differs from the release pin")
    contents = {}
    for name, entry in expected.items():
        path = root / name
        _regular(path)
        data = path.read_bytes()
        mode = 0o755 if path.stat().st_mode & 0o111 else 0o644
        if mode != entry["mode"] or hashlib.sha256(data).hexdigest() != entry["sha256"]:
            raise DependencyError("dependency payload bytes or mode changed: " + name)
        contents[name] = data
    return contents


class _VerifiedModules(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    def __init__(self, namespace, root, contents):
        self.namespace, self.root, self.contents = namespace, root, contents

    def _name(self, fullname):
        suffix = fullname.removeprefix(self.namespace)
        return "yaml/" + (suffix[1:] if suffix else "__init__") + ".py"

    def find_spec(self, fullname, path=None, target=None):
        if fullname != self.namespace and not fullname.startswith(self.namespace + "."):
            return None
        name = self._name(fullname)
        # cyaml.py is preserved upstream evidence, but optional C-extension
        # execution is excluded. It otherwise imports ambient yaml._yaml.
        if name == "yaml/cyaml.py" or name not in self.contents:
            raise ModuleNotFoundError("pure-Python dependency has no " + fullname)
        spec = importlib.util.spec_from_loader(fullname, self, is_package=fullname == self.namespace)
        spec.origin = str(self.root / name)
        spec.has_location = True
        return spec

    def create_module(self, spec):
        return None

    def exec_module(self, module):
        name = self._name(module.__name__)
        exec(compile(self.contents[name], str(self.root / name), "exec"), module.__dict__)


def load_yaml(root=PAYLOAD):
    """Verify a release bundle and import it without replacing ambient modules."""
    contents = verified_bytes(root)
    namespace = "_synthesis_pyyaml_" + uuid.uuid4().hex
    finder = _VerifiedModules(namespace, Path(root), contents)
    sys.meta_path.insert(0, finder)
    try:
        return importlib.import_module(namespace)
    except Exception:
        for name in tuple(sys.modules):
            if name == namespace or name.startswith(namespace + "."):
                del sys.modules[name]
        raise
    finally:
        sys.meta_path.remove(finder)
