#!/usr/bin/env python3
"""project_format.py — versioned synthesis project formats.

Detects a project's on-disk format version and pull-migrates v1
(unmarked CONTEXT.md / REFERENCE.md / sessions/) to v2 (marker +
machine-readable state + sessions index). Migration is strictly
additive — no byte is modified or deleted — idempotent, and verified
by re-reading everything written.

Usage:
    project_format.py detect <project-dir>
    project_format.py migrate [--check] [--goal TEXT] [--status TEXT] <project-dir>

Exit 0 with a JSON report on stdout. Exit 2 on unreadable input.
The full contract lives in the Phase F design doc and the
synthesis-project-management SKILL.md format section.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("project_format requires PyYAML (pip install pyyaml)")

ENGINE_VERSION = "1.0.0"
CURRENT_FORMAT = 2
MARKER_NAME = ".synthesis-project.yaml"
STATE_NAME = "CURRENT_STATE.json"
INDEX_NAME = "INDEX.md"
STATE_SCHEMA = 1

V1_LAYOUT = ("CONTEXT.md", "REFERENCE.md", "sessions")
HEADING_RE = re.compile(r"^##\s+(.+)$")
LOOP_RE = re.compile(r"\b(TODO|FIXME|XXX|OPEN|TBD)\b[:\s]+(.{0,120})", re.IGNORECASE)


def detect(project_dir: Path) -> str:
    """Return missing | v1 | v2 | partial | unknown."""
    if not project_dir.is_dir():
        return "missing"
    marker = project_dir / MARKER_NAME
    if marker.is_file():
        try:
            data = yaml.safe_load(marker.read_text(encoding="utf-8")) or {}
        except (OSError, ValueError):
            return "unknown"
        version = data.get("format_version")
        if version == CURRENT_FORMAT:
            return "v2"
        return "unknown"
    present = [(project_dir / name).exists() for name in V1_LAYOUT]
    if all(present):
        return "v1"
    return "partial"


def _utcnow() -> str:
    return datetime.now(timezone.utc).isoformat()


def _newest_period_file(project_dir: Path) -> Path | None:
    sessions = project_dir / "sessions"
    if not sessions.is_dir():
        return None
    files = sorted(sessions.glob("*.md"))
    if not files:
        return None
    return max(files, key=lambda p: p.stat().st_mtime)


def _skeleton_loops(newest: Path | None) -> list[dict]:
    if newest is None:
        return []
    loops = []
    try:
        text = newest.read_text(encoding="utf-8")
    except OSError:
        return []
    for match in LOOP_RE.finditer(text):
        loops.append(
            {
                "id": f"skeleton-{len(loops) + 1}",
                "text": match.group(2).strip(),
                "owner": "unassigned",
                "since": newest.stem,
                "unverified": True,
            }
        )
        if len(loops) >= 10:
            break
    return loops


def _sessions_index(project_dir: Path) -> str:
    sessions = project_dir / "sessions"
    lines = ["<!-- generated by project_format.py — do not hand-edit -->", ""]
    lines.append("# Sessions index")
    lines.append("")
    if sessions.is_dir():
        for path in sorted(sessions.glob("*.md")):
            if path.name == INDEX_NAME:
                continue
            try:
                text = path.read_text(encoding="utf-8")
            except OSError:
                continue
            headings = [
                HEADING_RE.match(line).group(1).strip()[:100]
                for line in text.splitlines()
                if HEADING_RE.match(line)
            ][:50]
            lines.append(f"## {path.stem} ({len(headings)} sessions)")
            lines.append("")
            for heading in headings:
                lines.append(f"- {heading}")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_marker(project_id: str, migrated_from: int) -> dict:
    return {
        "format_version": CURRENT_FORMAT,
        "id": project_id,
        "created": None,
        "migrated_from": migrated_from,
        "migrated_at": _utcnow(),
    }


def build_state_skeleton(
    project_dir: Path, goal: str = "", status: str = "unknown"
) -> dict:
    newest = _newest_period_file(project_dir)
    return {
        "schema": STATE_SCHEMA,
        "skeleton": True,
        "goal": goal,
        "status": status,
        "open_loops": _skeleton_loops(newest),
        "last_session": newest.stem if newest else None,
        "last_brief": "",
        "updated_at": _utcnow(),
    }


def validate_state(data: object) -> list[str]:
    """Return human-readable schema violations (empty means valid)."""
    errors: list[str] = []
    if not isinstance(data, dict):
        return ["state root must be an object"]
    if data.get("schema") != STATE_SCHEMA:
        errors.append(f"schema must be {STATE_SCHEMA}")
    if not isinstance(data.get("goal"), str):
        errors.append("goal must be a string")
    if not isinstance(data.get("status"), str):
        errors.append("status must be a string")
    loops = data.get("open_loops", [])
    if not isinstance(loops, list):
        errors.append("open_loops must be a list")
    else:
        for i, loop in enumerate(loops):
            if not isinstance(loop, dict):
                errors.append(f"open_loops[{i}] must be an object")
                continue
            for key in ("id", "text", "owner"):
                if not isinstance(loop.get(key), str):
                    errors.append(f"open_loops[{i}].{key} must be a string")
    return errors


def migrate(
    project_dir: Path,
    goal: str = "",
    status: str = "unknown",
    apply: bool = False,
) -> dict:
    """Check (default) or apply the v1 -> v2 migration. Returns a report."""
    found = detect(project_dir)
    if found == "missing":
        raise FileNotFoundError(f"no project directory: {project_dir}")
    if found == "v2":
        return {"from": 2, "to": 2, "noop": True, "verified": True, "added": []}
    if found != "v1":
        raise ValueError(f"cannot migrate a '{found}' project; need v1")
    added = [MARKER_NAME, STATE_NAME, f"sessions/{INDEX_NAME}"]
    if not apply:
        return {"from": 1, "to": 2, "noop": False, "verified": False, "added": added}
    # Additive means additive: never overwrite a file the project already
    # has. Kept files are validated instead of replaced.
    kept: list[str] = []
    if not (project_dir / STATE_NAME).exists():
        state = build_state_skeleton(project_dir, goal=goal, status=status)
        (project_dir / STATE_NAME).write_text(
            json.dumps(state, indent=2) + "\n", encoding="utf-8"
        )
    else:
        kept.append(STATE_NAME)
    if not (project_dir / "sessions" / INDEX_NAME).exists():
        (project_dir / "sessions" / INDEX_NAME).write_text(
            _sessions_index(project_dir), encoding="utf-8"
        )
    else:
        kept.append(f"sessions/{INDEX_NAME}")
    marker = build_marker(project_dir.name, 1)
    (project_dir / MARKER_NAME).write_text(
        yaml.safe_dump(marker, sort_keys=False), encoding="utf-8"
    )
    # Verify by re-reading everything written.
    errors: list[str] = []
    if detect(project_dir) != "v2":
        errors.append("marker did not re-read as v2")
    try:
        state_back = json.loads((project_dir / STATE_NAME).read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        errors.append(f"state did not re-read: {exc}")
    else:
        errors.extend(validate_state(state_back))
    if errors:
        # Roll back the marker so a failed migration reads as v1 again
        # and the next run retries instead of nooping on a lie. Added
        # state/index files stay (they are valid on their own); only the
        # version claim is withdrawn.
        try:
            (project_dir / MARKER_NAME).unlink()
        except OSError:
            errors.append("rollback failed: marker could not be removed")
        return {
            "from": 1, "to": 2, "noop": False, "verified": False,
            "added": added, "kept": kept, "errors": errors,
        }
    return {
        "from": 1, "to": 2, "noop": False, "verified": True,
        "added": added, "kept": kept,
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Detect and migrate project formats.")
    sub = parser.add_subparsers(dest="command", required=True)
    p_detect = sub.add_parser("detect", help="print the format version")
    p_detect.add_argument("project_dir")
    p_migrate = sub.add_parser("migrate", help="migrate v1 to v2")
    p_migrate.add_argument("project_dir")
    p_migrate.add_argument("--check", action="store_true", help="report only; write nothing")
    p_migrate.add_argument("--goal", default="")
    p_migrate.add_argument("--status", default="unknown")
    args = parser.parse_args(argv)
    try:
        if args.command == "detect":
            print(json.dumps({"format": detect(Path(args.project_dir))}))
        else:
            report = migrate(
                Path(args.project_dir),
                goal=args.goal,
                status=args.status,
                apply=not args.check,
            )
            print(json.dumps(report, indent=2))
            if report.get("errors"):
                return 1
    except (OSError, ValueError) as exc:
        print(f"project_format: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
